scylladb/scylla-ccm

ccmlib/cluster.py
Comment commitlog_sync_batch_window_in_ms parameter configuration for  Cassandra cluster because of Cassandra fails on None value. It expects "NaN".
=> Comment commitlog_sync_batch_window_in_ms parameter configuration for  Cassandra cluster

ccmlib/cluster.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Currently, node.stop(), and cluster.stop() which uses it, are hard-coded
to allow Scylla 127 seconds (=2^7-1), just a bit over two minutes, to
shutdown before failing. In some tests, see for example
https://github.com/scylladb/scylla/issues/4019, we know that we need more
than that time for the shutdown to complete.
So this patch makes the waiting time configurable, via an optional parameter
"wait_seconds" which defaults to the previously hard-coded 127 seconds and
can now be set to any number of seconds.
Signed-off-by: Nadav Har'El <nyh@scylladb.com>
=> node or cluster stop: make timeout configurable

ccmlib/cluster.py
Uncomment commitlog_sync_batch_window_in_ms parameter configuration for Cassandra cluster. We don't need to use this parameter
=> Revert of PR #116

ccmlib/scylla_node.py
Otherwise, all nodes will use the default /var/lib/scylla/view_hints.
=> scylla_node.py: Add view_hints_directory option

ccmlib/scylla_node.py
Allow different nodes to share cpus without a performance penalty. This allows increasing utilization when running mulitple test clusters in parallel.
Commit 6a3225e28701cff3a0b098212baddfb1761e04bd reverted it, but forgot to explain why. If there are problems, we should fix them.
=> node: use overprovisioned flag if no cpuset

ccmlib/scylla_node.py
Use SIGSTOP to pause a scylla process and use SIGCONT to resume. They
are useful to simulate a node down faster than acutally to kill a node and
restart later.
=> ScyllaNode: Add pause and resume support

ccmlib/node.py
Currently when running `node.stress()` there is no handling of the return code of  `cassandra-stress` command, so when it exists with error code > 0 we never catch this.
=> Fix stress return code

ccmlib/node.py
Addressing issue: https://github.com/scylladb/scylla/issues/4259
Collecting stdout/stderr of the stress process and printing them when we have an error.
Current stress method behavior isn't changed.
=> Collecting stress stdout/stderr and printing when error

ccmlib/node.py
Decided to allow passing stdout/stderr to stress method in order not to break the current functionality of 
other tests
=> Fix #137: adding support to pass stdout/stderr to stress method

ccmlib/scylla_node.py
seem like the cassandra node.py had a safe guard in place, that wasn't ported into scylla_node.py
I think this should do the trick
=> Fix scylla-dtest#854, make c* env thread safe

ccmlib/node.py, ccmlib/scylla_node.py
In dtest, we use node.start(wait_for_binary_proto=True) to make sure the
node can be started with no problem. However, if the scylla process
terminated in the boot up process,
node.start(wait_for_binary_proto=True) will wait for
node.wait_for_binary_interface() to wait for the log saying cql server is
started but since the scylla process is killed, this log will never come
and watch_log_for() will time out in 10 minutes.
Such 10 minutes wait is unnecessary, with this patch
node.start(wait_for_binary_proto=True) will fail the test immediately
when scylla process is terminated.
=> node.py: Fail node.start() immediately if scylla process terminated

ccmlib/node.py
To be used for associating coredump files with old pids.
See scylladb/scylla-dtest#900
=> node: maintain old_pids list

ccmlib/scylla_cluster.py
scylla-manager configuration file has been updated
drop the --developer-mode flag
force logging to stderr
following this change the following works
export SCYLLA_EXT_OPTS="--scylla-manager=...."
ccm create scylla-3 --scylla --vnodes -n 3 --install-dir=..
ccm start
ccm sctool cluster  add  --host 127.0.0.1 --name a
ccm sctool status  --cluster a
Signed-off-by: Shlomi Livne <shlomi@scylladb.com>
=> update scylla-manager support for manager 1.4

ccmlib/scylla_node.py
We're trying to understand why the socket is not available.
It might be in use by a stale scylla process so try to find
any running scylla process using the cluster ip prefix.
Its path includes the cluster test directory that could help
understand which test case started it.
Ref #145
=> scylla_node: print offending processes when socket is unavailable

ccmlib/node.py
DEBUG and TRACE messages may include intermediate printouts that
shouldn't be taken into account as these logging levels are optional.
Seen with commitlog_test:TestCommitLog.test_commitlog_replay_on_startup
when it looks for no occurances of " 0 replayed mutations", but
these are printed validly by DEBUG log messages, causing the test
to fail with DEBUG=true.
=> node: grep_log should only look at INFO/ERROR messages

ccmlib/cluster_factory.py, ccmlib/common.py, ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Address following warning:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated
Please read https://msg.pyyaml.org/load for full details.
Fixes #142
=> fix yaml load warning

ccmlib/cluster.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
When stopping more than one node in parallel and waiting for other to notice
we want to skip nodes that may be stopping concurrently.
Provide an optional other_nodes parameter for the caller to pass
only those nodes that require noticing.
=> cluster, node: support optional other_nodes for wait_other_notice

ccmlib/scylla_cluster.py
As seen on the lab machines, when running a number of tests
in parallel (5) and using a spinning disk, 5 minutes are not
enough for clusters to start.  Seen normal times in the order of
8 minutes, so enlarge the timeout to 10 minutes to provide
additional slack.
=> scylla_cluster: enlarge start timeout

ccmlib/cluster_factory.py, ccmlib/common.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_node.py, tests/test_cmds.py
YAML docs mention straight in the beginning:
> Warning: It is not safe to call yaml.load with any data received from
> an untrusted source! yaml.load is as powerful as pickle.load and so may
> call any Python function. Check the yaml.safe_load function though.
Many developers choose to use `yaml.load`. Probably, the result of people
using IDEs which offer completions in alphabetical order. It's easy to
do:
import yaml
yaml.(here comes a drop down list of options)
add_constructor
...
...
load
....
....
#safe_load is hidding here ...
It's easy to use without ever knowing how dangerous this could be.
This commit replaces all occurences of `yaml.load` with
`yaml.safe_load`.
=> YAML load isn't safe, opt to use safe_load

ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/command.py, ccmlib/common.py, ccmlib/scylla_cluster.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py
Also added optinal JAVA_TOOLS_DIR, so we don't need to create symlink to inside resources/cassandra to the java tools.
building java-tools:
```bash
./reloc/build_reloc.sh
./scripts/create-relocatable-package.py --version 3.11.3-SNAPSHOT scylla-java-tools-3.0.5.tar.gz
```
building jmx:
```bash
mvn package
./scripts/create-relocatable-package.py scylla-jmx-3.0.5.tar.gz
```
Inside dbuild we can build like that:
```bash
python3 scripts/create-relocatable-package.py --mode release scylla-3.0.5.tar.gz
mkdir scylla-3.0.5
tar xvvf temp.tar.gz -C scylla-3.0.5
```
And then use CCM like those options:
```bash
export JAVA_TOOLS_DIR=/home/fruch/Projects/scylla-java-tools
ccm create fruch --install-dir=/home/fruch/Projects/scylla-next/scylla-3.0.5
ccm populate -n 1
ccm node1 start
ccm create fruch …
```
=> Add support for using scylla relocatable packages

ccmlib/node.py
note this might break IPv6 IP tests
=> Use IPs instead of localhost for nodetool commands

ccmlib/cmds/cluster_cmds.py, ccmlib/common.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py, scylla_ccm_env.sh
since https://github.com/scylladb/scylla/commit/698b72b5018868df6a839d08fd24c642db97ffcd#diff-3fbb47e318cd8802bd325e7da9aaabe8 
relocatable usage in ccm is broken, this PR should address it
=> Fix relocatable to use install.sh (fixes #169)

ccmlib/scylla_node.py
is_running includes also decommissioned nodes that won't notice
that the new node is running.
Test: concurrent_schema_changes_test.py:TestConcurrentSchemaChanges.decommission_node_test using `wait_other_notice=True` when starting new node after decommission.
=> scylla_node: start: wait_other_notice only for live nodes

ccmlib/scylla_repository.py
install.sh command line arguments has been change recently
and broke ccm relocatable support
=> Fix relocatable packages to work with master version

ccmlib/scylla_node.py
If gently stopping the node failed retry with signal.SIGQUIT
Aborting is intended to generate a core dump
so the reason the node didn't stop normally can be studied.
Refs scylladb/scylla#4384 scylladb/scylla#5020
Test: `bootstrap_test:TestBootstrap.start_stop_test`
and the same with instrumenting scylla to hang on shutdown
=> Force core if stop gently failed

ccmlib/scylla_node.py
This method is called from node.stop() and we've seen cases where
this file was not found.
Move the call to a more specific place where we want to kill scylla-jmx
And since this is not critical at this point do not throw exception
if the file not found (we should have the pid from when starting
scylla-jmx).
See [cql_tests/TruncateTester/truncate_after_restart_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/278/testReport/cql_tests/TruncateTester/truncate_after_restart_test/):
Note that the exception message is misleading as we're stopping the node and the exception mentions starting node scylla-jmx, I guess for historical reasons.
```
Problem starting node node2 scylla-jmx due to [Errno 2] No such file or directory: …
```
=> scylla_node: _update_jmx_pid: don't throw exception if scylla-jmx.pid not found

ccmlib/scylla_node.py
agent configuration has change from using the path of scylla yaml
to need to specify the api address and port of scylla
=> Add `api_address` and `api_port for the scylla manager agent

ccmlib/scylla_node.py
`GNUTLS_SYSTEM_PRIORITY_FILE` defaults `/opt/scylladb/libreloc/gnutls.config`
by the relocatable scripts when replaceing scylla binary with a shell script
which was causing all SSL related tests in dtest to fail when using
relocatable packages
Fixes scylladb/scylla-dtest#1150
=> Configure `GNUTLS_SYSTEM_PRIORITY_FILE` correctly when using relocatable

ccmlib/cluster.py, ccmlib/scylla_cluster.py
Currently we always use default 'all' for internode_encryption parameter.
This patch made this configurable, we will use it to cover more configuration in dtest.
=> enable_internode_ssl: support to assign internode_encryption

ccmlib/node.py
was breaking tests that was using limit or throttle in the stress command
with the following error:
```
======================================================================
ERROR: add_50_nodes_test (update_cluster_layout_tests.TestLargeScaleCluster)
----------------------------------------------------------------------
File "/jenkins/workspace/scylla-master/debug-jobs/byo_build_tests_dtest/scylla-dtest/update_cluster_layout_tests.py", line 1602, in add_50_nodes_test
t.result()
...
File "/jenkins/workspace/scylla-master/debug-jobs/byo_build_tests_dtest/scylla-ccm/ccmlib/node.py", line 1110, in stress
**kwargs)
TypeError: unsupported operand type(s) for ** or pow(): 'bool' and 'dict'
```
=> Missing comma in `node.stress()`

ccmlib/common.py
this isn't a big issue, but it would give us the ability to get the actual branch version.
not really helpful in master, where it's `666.development`
=> `SCYLLA-VERSION-FILE` is in a diffrent location in reloc packages

ccmlib/scylla_node.py
Those are broken, and works better with the functions in Node
It's rarly used in dtest, but some java-driver tests are using this
=> Remove pause() and resume() from ScyllaNode

ccmlib/cluster.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Fixes https://github.com/scylladb/scylla-dtest/issues/1189
We hit the following path:
```
Stacktrace
File "/usr/lib64/python2.7/unittest/case.py", line 422, in doCleanups
function(*args, **kwargs)
File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 234, in stop_node3
node3.stop()
File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 602, in stop
if not self.wait_until_stopped(wait_seconds):
File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 543, in wait_until_stopped
if not self.is_running():
File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 294, in is_running
self.__update_status()
File …
```
=> node cleanups: update_config, new_node, update_pid

ccmlib/scylla_node.py
Mark scylla waiter threads as "daemon" to avoid blocking the main
thread on shutdown.
A non-daemon thread has to die before the main thread
can continue, so if, for whatever reason, there is no
tear-down at shutdown, the main dtest thread could get
stuck forever.
=> Mark scylla waiter threads as "daemon"

ccmlib/node.py
`[dead|DOWN]` matches any letter in the brackets.
The correct regular expression is `(dead|DOWN)` that
matches either of the strings `dead` or `DOWN`.
=> node: watch_log_for_death: fix regex

ccmlib/node.py, ccmlib/scylla_node.py
one that restarts the node's manager agent
and one that returns the node's true datacenter name using nodetool info (unlike the false one that ccm bequeaths it)
=> Added two functions to the node class

ccmlib/common.py, ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Timing in debug mode is much slower than release/dev modes and
the default reactor stall threshold of 200 ms produces
a lot of false positives. Therefore, increase it in this case using
the `--blocked-reactor-notify-ms` option to 5 seconds.
=> Increase debug blocked reactor notify ms

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Provide additional start_nodes and stop_nodes methods that can be used to start/stop multiple nodes in parallel.
Fix #212
=> Refactor cluster start and stop

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Infrastructure for changing the dtest default to `wait_for_binary_proto=True` and wait_other_notice=True` when starting cluster and single nodes.
=> Force wait for cluster start

ccmlib/scylla_cluster.py
The `no_wait` parameter in `start_nodes` was not used anywhere.
This commit passes the flag to `node.start(...)` and changes the default
value to `True`, because that's what `node.start(...)` previously used.
=> scylla_cluster: handle no_wait flag

ccmlib/scylla_repository.py
new names in S3 folder `unstable/master:2020-02-15T03:02:19Z`
since it has `:` in it, we need to split only on the first one
=> fix SCYLLA_VERSION parsing of new format in S3 folders

ccmlib/scylla_repository.py
new foramt like `unstable/master:2020-02-15T03:02:19Z` is breaking
the install.sh causing patchelf to coredump
=> Fix direcorty name for new date format in S3

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
both in the agent and the manager's yaml
=> Scylla manager: set an address for the debug server

ccmlib/scylla_node.py
Current message introduced in #225 is not always printed.
For example, in:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/90/artifact/logs-debug.2/1584197488046_replace_address_test.TestReplaceAddress.replace_shutdown_node_test/node4.log
`JOINING: Starting to bootstrap` is always printed by `storage_service::bootstrap`
so use it instead.
=> ccmlib/scylla_node: _start_scylla: fix expected bootstrap message

ccmlib/scylla_node.py
Accomodate for the default ring_delay_ms timeout of 300 seconds.
=> scylla_node: increase wait_for_binary_interface timeout

ccmlib/scylla_cluster.py
In an effort to make manager repairs faster, I set segments_per_repair to 16 in scylla_manager.yaml
=> fix(scylla_manager): set segments_per_repair=16 in manager yaml

ccmlib/scylla_node.py
When raising TimeoutError exception, the caller must provide the `data` argument.
Hit in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/testReport/replace_address_test/TestReplaceAddress/replace_first_boot_test/
```
File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 281, in _start_scylla
self.wait_for_binary_interface(from_mark=self.mark, process=self._process_scylla, timeout=420)
File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 494, in wait_for_binary_interface
self.watch_log_for("Starting listening for CQL clients", **kwargs)
File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 448, in watch_log_for …
```
=> ccmlib/scylla_node: wait_for_bootstrap_repair: TimeoutError requires argument

ccmlib/scylla_node.py
Now that repair-based node operations are disabled by default
since scylladb/scylla@b8ac10c4514d2ff099a288dfa3cb6f938b42d582,
We see failures like https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/147/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_extend_test/
```
File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
yield
File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
testMethod()
File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 598, in mv_populating_from_existing_data_during_extend_test
self._mv_populating_from_existing_data_during_changes_test('add node', nodes=4, rf=3, mvs=10, …
```
=> ccmlib/scylla_node: extend wait_for_bootstrap_repair to cover streaming

ccmlib/common.py
The dtest code that uses get_version_from_build via cluster.version()
expects the version string to be numeric based - 2.2, 3.0, etc.
And it is no use returning something like '666.development' or
'9999.enterprise_dev'.  So for scylla, just return '3.0' as returned
by get_scylla_version when no specific version is found.
In particular, '20XX.1.*' release versions mess up tests that
compare them as greater than '2.2', as seen in e.g.:
https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/dtest-release/2/testReport/thrift_tests/TestMutations/test_describe_keyspace/
```
File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
yield
File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
testMethod()
File …
```
=> Fix get_version_from_build

ccmlib/scylla_cluster.py
since port 9090 is used by scylla-monitoring stack
we are change this port to default to 5080
=> Change manager-server port to 5080

ccmlib/scylla_cluster.py
A change in scylla moves this log message onto a different logger
so the strict pattern won't match.
=> scylla_cluster: start_nodes: make watch_log_for "Schema version changed" looser

ccmlib/scylla_cluster.py
Wait for previous nodes' `"node is now in normal status"` message
to let is finish bootstrapping if it needs to.
Otherwise, the 60 seconds timeout on the booting node may not be sufficient
as seen in dtest-debug:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/609/artifact/logs-debug.2/1601767547770_internode_ssl_test.TestInternodeSSL.putget_with_reloaded_certificates_test/node3.log
```
INFO  2020-10-03 23:14:45,477 [shard 0] storage_service - Checking bootstrapping/leaving nodes: tokens 256, leaving 0, sleep 1 second and check again (59 seconds elapsed)
...
ERROR 2020-10-03 23:14:48,151 [shard 0] init - Startup failed: std::runtime_error (Other bootstrapping/leaving nodes detected, cannot bootstrap while consistent_rangemovement is true)
```
Signed-off-by: …
=> scylla_cluster: start_nodes: start nodes in parallel more conservatively

ccmlib/cluster.py, ccmlib/common.py, ccmlib/node.py, ccmlib/scylla_node.py
from `pkg_resources` import `parse_version` and use to to compare structured versions conforming to https://www.python.org/dev/peps/pep-0440/.
This will provided the following ordering:
`'i.j(.|-)dev[N]' < 'i.j.rc[N]' < 'i.j.k' < i.j(.|-)post[N]`
So we can use 'i.j.dev' for the master branch, before it's forked to `branch-i.j` that will initially versioned as `i.j.rc0` and so on until it becomes `i.j.0`.
Cc @avikivity @penberg @fruch 
See also usage in https://github.com/bhalevy/scylla-dtest/commits/parse_version
=> Use parse_version to compare versions conforming to PEP-440

ccmlib/node.py, ccmlib/scylla_node.py
Add a timeout parameter to nodetool since we saw to hanging in
https://github.com/scylladb/scylla/issues/7244
Currently, the default timeout is `None`, so the behavior remains backward compatible
and nodetool will be waited for forever.
Only the explicit paths seen in https://github.com/scylladb/scylla/issues/7244 pass a timeout in this series.
We may want to consider as a follow up setting the default timeout to a long, but not infinite, timeout, like 10 minutes or more, so that if it hangs, the test will fail and if scylla hangs we can kill it and get a core dump.
=> nodetool: add timeout

ccmlib/scylla_docker_cluster.py
from `get_path` i got the last part and added to the `docker_name` to make dockers unique..
the path when running from dtest will be generated by the framework and the path is the only difference between the "clusters"
=> Docker ccm fix docker name

ccmlib/node.py, ccmlib/scylla_docker_cluster.py, tests/conftest.py, tests/test_scylla_docker_cluster.py
* Create `docker_image` variable under `Node` class
* Change the `jmx_port` field under ScyllaDockerNode from
int to string (because the old CCN code expected to get
string)
* stress method - Convert the `stress` variable to list and 
set None value for `cwd` variable in case the cluster is 
docker
=>     feature(.node.py): Fixing stress command for docker cluster

ccmlib/cluster.py, ccmlib/common.py, ccmlib/node.py, ccmlib/scylla_node.py
Add a logging facility to Cluster class.
Provide optional `ccm_logger` and `ccm_log_level` parameters provided for integration with dtest logging.
See https://github.com/bhalevy/scylla-dtest/commit/9dac036a8e8ff5766559f3d158b872972cee4bec for planned usage.
Fixes #214
Note: this series depends on https://github.com/scylladb/scylla-ccm/pull/253
that was recently merged, hence it's based off of `scylla-ccm/next`.
Output example:
```
(env) $ PRINT_DEBUG=true CASSANDRA_DIR=../scylla/build/debug NOSE_PROCESSES=2 SCYLLA_EXT_OPTS="--smp 2" nosetests -s -v --process-timeout=7200 cfid_test:TestCFID.cfid_test
2020-10-18 10:55:35.257537 going to run tests in parallel
2020-10-18 10:55:35.257622 using the RandomClusterIdAllocator
2020-10-18 10:55:35.284624 cfid_test.py:TestCFID.cfid_test - cluster ccm …
```
=> Add ccm cluster logging facility

ccmlib/node.py
a change in 373a62bd54d2377708f7f527937714730ed3a842 was missing
some small but importent part.
=> nodetool timeout: timeout missing on `communicate()` call

ccmlib/scylla_repository.py, setup.py
To skip running systemctl in scylla-ccm, rewriting install.sh by sed can break
the script, we can use --packaging option instead.
Fixes #249
=> ccmlib/scylla_repository: use --packaging option, drop sed to prevent running systemctl

ccmlib/scylla_repository.py
This hack didn't work when I added support in install.sh
for ubsan-suppressions.supp file as it looked for a `"$prefix` string
to substitute (with a leading double quotation mark).
As Avi explained in https://github.com/scylladb/scylla/issues/4949#issuecomment-724786194,
the hack is not required, so undo it by passing the right
`--prefix` option to install.sh, with no `--root` option, as
we're installing it relative to the host real root directory.
Refs scylladb/scylla#4949
=> ccmlib/scylla_repository: run_scylla_install_script: undo sed $prefix hack

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
As seen in many debug tests, we're too quick to declare timeout on the stopping node and the core dump indicates the node is still busy flushing.
This will be more noticeable now that https://github.com/scylladb/scylla-dtest/pull/1763 is merged.
Increase the timeout to 10 minutes in debug mode to let the node have enough time to stop gracefully.
Test: cql_tracing_test.py:TestCqlTracing.tracing_startup_test (debug)
```
2020-11-19 11:34:08.814563 cql_tracing_test.py:TestCqlTracing.tracing_startup_test - cluster ccm directory: /local/home/bhalevy/.dtest/dtest-3jw7vgbr
2020-11-19 11:34:08.814709 cql_tracing_test.py:TestCqlTracing.tracing_startup_test - Starting Scylla cluster from directory ../scylla/build/debug
2020-11-19 11:34:08.818760 …
```
=> wait_until_stopped: increase wait time in debug mode

ccmlib/scylla_repository.py
For enterprise, the product name in packages' name is `scylla-enterprise`, but
we are using a hardcode base url and product name. This patch supported to
assign the product name by SCYLLA_PRODUCT env variable, and choose a correct
base url.
For 2020.1, the product name in packages' name is `scylla`, so we don't need to
backport this patch to 2020.1
Signed-off-by: Amos Kong <amos@scylladb.com>
=> fix(ccmlib/scylla_repository.py): fix hardcode product name and base url

ccmlib/common.py, ccmlib/scylla_cluster.py, ccmlib/scylla_docker_cluster.py
Using boto3.client is not thread safe. These special classes contain additional
meta data that cannot be shared between threads. 
When run relocatable packages download in parallel in threads, it may fail (not every run) with error:
```
15:02:23  Traceback (most recent call last):
15:02:23    File "/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/dtest.py", line 640, in setUp
15:02:23      self.cluster = self.get_cluster(version=self.cassandra_version)
15:02:23    File "/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/upgrade_test.py", line 42, in get_cluster
15:02:23      self.download_all_relocatables()
15:02:23    File "/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/upgrade_test.py", line 73, in download_all_relocatables
15:02:23 …
```
=> Run boto3 client in parallel

.github/workflows/integration-tests.yml, ccmlib/common.py, tests/conftest.py, tests/test_config.py, tests/test_scylla_relocatable_cluster.py, tests/test_version_parsing.py
new function that can show the full version of relocatable/source runs (including the date and git sha)
we want this to be part of the data collect per dtest run.
Closes: #252
=> introduce 'common.get_scylla_full_version'

ccmlib/scylla_repository.py
Wronly send parameter when scylla-manager isn't defined
```
--scylla-manager=None
```
=> fix(scylla_repository): wrong logic when scylla-manager isn't

ccmlib/scylla_repository.py, ccmlib/utils/download.py, pytest.ini, scripts/download_enterprise.sh, scripts/download_master.sh, scripts/download_rc_version.sh, setup.py, tests/test_scylla_download.py, tests/test_scylla_repository.py
* Introduced new function to download from http and from s3
* Both have progress bar with `tqdm` package
* Both should worker much faster then current ones
Demo of it in action:
https://asciinema.org/a/yQZgxrjv7sb6b2Shp0IK77CP9
feature(helper_scripts): script to download branched version and RCs
since recently some of the folder structure in our S3 for relocatable packages
changed, we are introducting helper script for whom need quickly get those versions
Example of taking a release canidate of 4.3 branch:
[![asciicast](https://asciinema.org/a/382888.svg)](https://asciinema.org/a/382888)
=> feature(download): Speedier downloads from s3

ccmlib/node.py
Since we were using specific user profile file,
use `cwd` was starting the process from the wrong direcotry
we were excpecting, this logic can be removed
Fixes: scylla-dtest/issues/1853
=> Node.stress: remove uses of cwd

ccmlib/scylla_repository.py, tests/test_scylla_repository.py
After move to new location usage:
`$ SCYLLA_VERSION=unstable/master:2021-01-18T15%3A48%3A13Z ./scripts/run_test.sh`
failed with error:
```
File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/scylla_repository.py", line 175, in setup
tmp_download, 'scylla-core-package'))
File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/scylla_repository.py", line 289, in download_version
download_file(url=url, target_path=target,verbose=verbose)
File "/home/abykov/Projects/scylladb-project/scylla-ccm/ccmlib/utils/download.py", line 110, in download_file
resp.raise_for_status()
File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for …
```
=> fix(scylla_repository): Fix link relocatable_url_base

ccmlib/common.py
in some cases when used a specific local files, it would return None, and not
default `release`
=> fix(scylla_extract_install_dir_and_mode): never to return a None scylla_mode

ccmlib/cluster.py
As part of moving scylla-dtest to pytest, we want this function
so we can have closer feedback in logs of test when there are errors
in the scylla logs.
Ref: https://github.com/riptano/ccm/commit/24e14bc81109e3c9f5260aa46e0f57f85d548dc9
Ref: https://github.com/riptano/ccm/commit/50eb217ef1b5b4242e8526c350622691f12931e2
=> feature(actively_watch_logs_for_error): backport from cassandra-dtest

ccmlib/scylla_repository.py
seems like the fix in 4571bc7c3835e8a1632d571f7beff707c96b4563 wasn't enough
and not accurate, and was breaking the manager dtest jobs
since `SCYLLA_EXT_OPTS` was defined, while the logic assume it would be defined
only when manger is used locally
=> fix(scylla_repository): logic for setup of manager wasn't correct

ccmlib/node.py
The issue here is wrong path to cassandra/bin folder
It affects on the sstablesplit_test only. I didn't find other test that use it.
It's not connected to pytest.
Actually this test is not running, not part of the scylla_tests file
=> fix cassandra bin path in node.run_sstablesplit

ccmlib/scylla_node.py, tests/test_scylla_relocatable_cluster.py
When nodetool command get timeout, we try to send `SIGQUIT` to get
a threaddump inforamtion into scylla-jmx stdout.
Close: #303
Ref: https://github.com/scylladb/scylla/issues/7991#issuecomment-771468592
=> fix(#303): collect more info when nodetool raises `TimeoutExpired`

ccmlib/scylla_node.py
The `SIGQUIT` is follow too soon by a forcefull kill, i.e. we don't let
the process enough time to print the output to stdout
Close: #303
Ref: https://github.com/scylladb/scylla/issues/7991#issuecomment-771468592
=> fix(#304): wait a bit more when killing scylla-jmx on timeout

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Currently we need to wait the full `node.watch_log_for` timeout
(600 seconds) to detect that a node failed during startup.
Pass the last_node process to `watch_log_for` so it
can fail as as it detects that the node terminated.
And in scylla_start: increase timeout in debug mode
to prevent test failures due to slow start when scylla is resharding sstables when started.
Test: materialized_views_test:TestMaterializedViews.{interrupt_build_process_with_resharding_low_to_half_test,interrupt_build_process_and_resharding_low_to_half_test}
=> Adjust scylla start timeout

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
In addition to 23880da688cc8f3bc2b0ba5d17363c4edd42a138
cluster.stop_nodes also needs to ignore node.is_running
to kill scylla-jmx, e.g. when the cluster is stopped
in the end of a dtest.
This change calls node.do_stop on all nodes to be stopped,
regardless if they are running or not (as it is possible
that the scylla process would have already exited, or
failed to start), and then call node.wait_until_stopped
if wait=True on all the above nodes.  wait_until_stopped
makes sure to kill all processes, and to get a core dump
from scylla if dump_core=True (derived from gently).
Dtest: secondary_indexes_test.py:TestSecondaryIndexes.test_insert_data_after_recreating_ks
=> scylla_cluster: stop_nodes: ignore node.is_running

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_docker_cluster.py, tests/ccmcluster.py, tests/conftest.py, tests/test_scylla_cmds.py
Seems that since relocatable was introduced, not many people were using
the ccm commandline for it, and this was broken for relocatable packages
now the `scylla_version` is persisted and any other following ccm commands
now would know it's relocatable version, and could work correctly.
=> fix(ccm add): support `ccm add` for relocatable package

ccmlib/scylla_node.py
Currently, the functions applies options given in SCYLLA_EXT_OPTS
only if they aren't already present in jvm_args.
However, the environment may provide the option and its arg
as --opt=arg, and then it is not found in jvm_args, that is given
as a list with the option string and its argument as two separate
entries.
scylladb/scylla-dtest@092465a7b8221ba4bfd69b8f7a47606b6ac5147d
added ['--abort-on-lsa-bad-alloc', '0'] to jvm_args,
but the jenkins environement sets `--abort-on-lsa-bad-alloc=1`
in SCYLLA_EXT_OPTS, causing a conflict, and the node doesn't start.
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/762/artifact/logs-release.2/1615353430139_toppartitions_test.TestTopPartitions.test_read_by_gause_key_distribution_for_compound_primary_key_and_large_rows_n …
=> scylla_node: start: correctly process --opt=value in SCYLLA_EXT_OPTS

ccmlib/common.py, ccmlib/scylla_repository.py
If few tests start in parallel, run same cluster version and download same
relocatable packages, add mechanism to prevent failure when copy the
packages to the version folder. Create placeholder file when start
downloading and remove it once the process has been completed
=> Prevent parallel relocatable packages download to the same folder

ccmlib/scylla_node.py
Scylla nodes started by ccm run in an overprovisioned environment
with limited performance disks. To reduce load on the disks, use
the new --kernel-page-cache option. This will reduce the likelihood
of timeouts on more intensive tests.
=> node: use the kernel page cache for ccm scylla nodes

ccmlib/scylla_repository.py
Version number format in relocatables name has been changed from
'd.d.d-' to 'd.d.d.'. Due this change ccm failed to find the
release relocatables for 4.4 version. Ajust the regex
=> fix(version format): version number format in relocatables name

ccmlib/node.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py
This commit fixes the issue: https://github.com/scylladb/scylla-ccm/issues/318
Start Scylla node with --kernel-page-cache argument if the version is 4.5 or higher
Upgrade tests are passed: https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/502/console
=> Starting scylla with --kernel-page-cache from 4.5 version and above only

ccmlib/scylla_cluster.py
Due to recent changes in scylla manager, the migrate_dir config option
should not be used if using manager version that is older than 2.5
or if using a master build before 20210430.2217cc84.
I made sure ccm will not config this option unless using supporting versions
=> fix(manager): config migrate_dir option only on supporting versions

ccmlib/node.py
set_install_dir() is used to upgrade old installation, we should skip
to create dest directory and replace existing file.
Signed-off-by: Amos Kong <amos@scylladb.com>
The following tests used set_install_dir() to upgrade scylla.
```
upgrade_tests/cql_tests.py:TestCQL.select_list_key_multi_row_test
upgrade_tests/cql_tests.py:TestCQL.select_set_key_multi_row_test
upgrade_tests/cql_tests.py:TestCQL.select_map_key_multi_row_test
upgrade_tests/cql_tests.py:TestCQL.select_list_key_single_row_test
upgrade_tests/cql_tests.py:TestCQL.select_set_key_single_row_test
upgrade_tests/cql_tests.py:TestCQL.select_map_key_single_row_test
```
=> set_install_dir: support to upgrade old installation

ccmlib/scylla_cluster.py
new in manager 2.4
Added the option to use the dry-run attribute with the agent's download-files command
=> feature(manager-agent): download-files' dry-run attribute

ccmlib/scylla_node.py
Pull #321 introduced code to check the node version using
SCYLLA-VERSION-FILE (and LooseVersion). However,
when testing scylla compiled from source,
SCYLLA-VERSION-FILE is not available.
Try to get the node version using node_install_dir_version
and if not successful, fallback to cluster.version()
to decide whether to add the --kernel-page-cache command
line option.
Also, it uses parse_version rather than LooseVersion
for version comparison as we already changed version
checking code everywhere to use the latter that is
suitable for our versioning conventions, unlike
LooseVersion.
`node_install_dir_version` was changed from `@property`
to a regular method so it can call self.debug in
case SCYLLA_VERSION_FILE wasn't found.
Refs #321
Fixes #318
Dtest: …
=> scylla_node: start: do not rely on SCYLLA-VERSION-FILE

ccmlib/node.py
Looks like bad merge done in cef74199
=> node: delete duplicate definitions of logging methods

ccmlib/scylla_cluster.py, ccmlib/scylla_repository.py
Due to changes in the manager build process, the old manager rpms are no longer
usable by ccm. As such, I modified the manager installation process to use the
manager relocatable tar files instead.
=> refactor(manager installation): modified to support new tar.gz format

ccm
On some (all?) modern Linux distros /usr/bin/python
still points to python2.
At the same time our code uses some Python3-specific features
like f-strings.
Hence we (still) need to be explicit about Python3.
Fixes #336
Signed-off-by: Vlad Zolotarov <vladz@scylladb.com>
=> ccm: explicitly use Python3 interpreter

ccmlib/scylla_node.py
import_bin_files() doesn't pass replace=replace to hard_link_or_copy
when copying scylla-jmx from a local installation, so node upgrade from
a local installation fails with a "file exists" error. Fix that.
Discovered when running upgrade_test.py with a local Scylla build.
=> fix(scylla_node): fix upgrade from local installation

ccmlib/scylla_node.py
scylladb/scylla@2cfc517 sets max_networking_aio_io_control_blocks to
50000 by default, causing us to run out of aio iocb slots and fail
starting in setup_aio_context.
Reduce it by default to 100 that is sufficient for testing
if not given a different value via jvm_args.
Fixes #334
=> scylla_node: start: set --max-networking-io-control-blocks=100 by default

ccmlib/scylla_repository.py
Latest version is 3.
We don't need fixes for scylla-ccm on this version.
=> increment supported relocatable package version

tests/test_scylla_cmds.py
since ddd36ff003781142443f59159a683fa7adb4f55e the url in the test
doesn't work anymore, and needed to change.
=> test_scylla_cmds.py: use new manager packages

.github/workflows/integration-tests.yml, ccmlib/scylla_docker_cluster.py, ccmlib/scylla_node.py, tests/test_config.py, tests/test_scylla_cmds.py, tests/test_scylla_docker_cluster.py, tests/test_scylla_relocatable_cluster.py
since b50e43f9325de43a90105346ae38437ecf178cc1 was introduced
the old scylla used isn't working, moving to newer version of scylla
moving to newer version of the docker image has other issues, disabling the
tests for now
=> Fix integration suite to pass

ccmlib/node.py
this was breaking `offline_tools_test.TestOfflineTools.test_sstableverify`
introduce by 54cf7b8e17508acbfb946f260f866fda8b0e4628
=> Fix Node.run_sstableverify to handle correctly get_tool response

ccmlib/scylla_node.py
It was reduced to 100 in b50e43f to deal with #334,
and then in 17567b52e it was restricted to version 4.7.dev and up.
But apparently the low value causes scylladb/seastar#976
This change increases it to a more reasonable value of 1000
and changes the version restriction to 4.6, since the bump
up to 50000 happened in scylladb/scylla@2cfc517874
which is in branch-4.6
Fixes #352
=> Increase the max-networking-io-control-blocks parameter

ccmlib/cluster.py
When there's more than 9 nodes in cluster,
nodes with number >9 are improperly sorted by nodelist() method
this causes errors in some tests when test relies on last node
in nodelist is the one with highest number
This fix converts node's dictionary to OrderedDict
=> fix(cluster.py): fix nodelist ordering

ccmlib/common.py, tests/test_common.py
since now package filename has arch where the mode was, this
function was return wrong the arch in some cases
=> common: fix `scylla_extract_mode` to handle new package name

ccmlib/scylla_node.py
* Reduce sleep to 50ms, and limit the `while` runtime to 30 seconds
* Bug ticket https://github.com/scylladb/scylla-dtest/issues/2429
=> improvement(scylla_node.py): Improving _wait_java_up method

ccmlib/repository.py, ccmlib/scylla_repository.py
In some race condition when multiple test are running at the same time,
we might fail to create directories
=> repository: fix directory creation failure

ccmlib/cmds/cluster_cmds.py, ccmlib/node.py
To treat backslashes as literal characters, otherwise they are parsed as escape patterns, causing deprecation warnings like:
```
../scylla-ccm/ccmlib/node.py:74
/home/bhalevy/dev/scylla-ccm/ccmlib/node.py:74: DeprecationWarning: invalid escape sequence \s
_sstable_regexp = re.compile('((?P<keyspace>[^\s-]+)-(?P<cf>[^\s-]+)-)?(?P<tmp>tmp(link)?-)?(?P<version>[^\s-]+)-(?P<number>\d+)-(?P<big>big-)?(?P<suffix>[a-zA-Z]+)\.[a-zA-Z0-9]+$')
../scylla-ccm/ccmlib/node.py:1263
/home/bhalevy/dev/scylla-ccm/ccmlib/node.py:1263: DeprecationWarning: invalid escape sequence \s
p = re.compile('^\s*([\d\.\,]+\d?)\s*\[.*')
../scylla-ccm/ccmlib/node.py:1267
/home/bhalevy/dev/scylla-ccm/ccmlib/node.py:1267: DeprecationWarning: invalid escape sequence \s
p = re.compile('^.*READ:\s*([\d\.\,]+\d?)[^\d].*') …
```
=> Use raw strings for regular expression patterns

ccmlib/scylla_cluster.py
This effectively reverts scylla_cluster: handle no_wait flag
since we need the default start to be safe and set `no_wait=True`
explicitly from tests that are proved to tolerate it.
Scylla start became faster since
scylladb/scylla@78d0cc4ab5ebd47f101ce78b79a30a48ee9f4b9b
and without this change, multi-node dtests tend to fail.
DTest: consistent_bootstrap_test.py::TestBootstrapConsistency::test_consistent_reads_after_bootstrap
(with --cassandra-dir)
Validating the debug log:
```
21:13:06,524 3398130 ccm                            DEBUG    cluster.py          :694  | test_consistent_reads_after_bootstrap: start_nodes: no_wait=False wait_for_binary_proto=True wait_other_notice=True force_wait_for_cluster_start=True
21:13:06,528 3398130 ccm                            DEBUG    cluster.py …
```
=> scylla_cluster: start with no_wait=False by default

ccmlib/node.py, ccmlib/scylla_node.py
Allow flushing a specified keyspace / table.
DTest: (modified) test_disable_autocompaction_schema
=> node: flush: add ks and table optional args

scripts/download_enterprise.sh, scripts/download_master.sh, scripts/download_release.sh
since the move to have the arch in the package name, the ccm code
is going to do a better job of selecting the correct packages to download
=> scripts/*: switch to let ccm download files

ccmlib/cluster.py, ccmlib/node.py, ccmlib/scylla_node.py
In Python, when passing a mutable value as a default argument in a function,
the default argument is mutated anytime that value is mutated.
Here, "mutable value" refers to anything such as a list, a dictionnary
or even a class instance.
Example:
```
def append(element, seq=[]):
seq.append(element)
return seq
>>> append(1)  # seq is assigned to []
[1]  # This returns a reference the *same* list as the default for `seq`
>>> append(2)  # => `seq` is now given [1] as a default!
[1, 2]  # WTFs and headaches start here…
```
=> fix(ccmlib/cluster.py): Removing mutable defaults argument

ccmlib/scylla_repository.py
I've seen that when using `unstable/master:2022-01-12T07:42:12Z`
we hit AWS api a few time looking for that version, even that it's
already cached, this moved the check into erlier stage to
make sure we are not calling any unneeded api, and slow test execution.
(at least local, in out CI the version string getting changed into something
else, and files are download not via CCM, and this issue doesn't affect it)
=> fix(scylla_repository): don't look in S3 if directory already exist

ccmlib/repository.py
The following code incorrect:
```python
while attempt < 3 and ret_val != 0:
...
```
From Python version 3.8+, the following warning message is shown:
```
ccmlib/repository.py:311: SyntaxWarning: "is not" with a literal. Did you mean "!="?
```
=> fix(ccmlib/repository.py): Fixing SyntaxWarning warning log

ccmlib/scylla_cluster.py
while working on scylladb/scylla-dtest#2455, setting `skip_wait_for_gossip_to_settle`
to 0, we've found out that we are not waiting for others on the first time
we boot a cluster, since no node is available before we start.
but while we start we need to add the started node so the next node
can actually use `wait_for_others` correctly.
=> scylla_cluster: add each nodes to marks after calling node.start()

ccmlib/node.py
Since recently for upgrade/rollback we started doing snapshots
rolling upgrade test started failing like this:
```
>                   assert len(sstable_versions) == 1, "expected all table format to be the same found {}".format(
sstable_versions)
E                       AssertionError: expected all table format to be the same found {'md', 'me', 'mc'}
E                       assert 3 == 1
E                         +3
E                         -1
```
turns out the `check_node_sstables_format` method was reading
also from the snapshots direcotry, hence the failure.
it was cause of wrong escaping of the filter find command.
=> node: check_node_sstables_format wasn't skipping snapshots

ccmlib/scylla_repository.py
current code for handleing diffrent architectures wasn't taking the
`scylla_product` into account, it was working fine, until recently
the lastest enterprise versio has multiple architectures.
=> fix(release_packages): downloading 2021.1 latest was failing

ccmlib/cluster.py, ccmlib/scylla_node.py
ccmlib **cluster.populate** method create nodes with
seeds, where each node have seeds all previous seeds
and itself
ex:
node1: node1
node2: node1, node2
node3: node1, node2, node3
the **cluster.set_configuration_options()** method rewrite the
scylla.yaml per node.
If it is called after **cluster.populate** method, but before
**cluster.start** method, **cluster.set_configuration_options()**
rewrite the node's scylla.yaml with seeds configuration all seeds:
node1: node1, node2, node3
node2: node1, node2, node3
node3: node1, node2, node3
for some feature, such seed configuration could affect cluster start
and cluster will not be started.
New method parameter is presented, which allow to return
all seeds node before provided node.
=> fix(get_seeds): return correct seed nodes after set_configuration_options changed.

ccmlib/scylla_node.py
Scylla does no longer print "JOINING:"
since scylladb/scylla@968b07052d6 (5.1.dev)
This causes a timeout as seen in e.g.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/8/testReport/materialized_views_test/TestMaterializedViews/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split027___test_add_dc_during_mv_insert/
```
materialized_views_test.py:469: in _add_dc_during_mv_change
run_in_parallel(proc_functions)
tools/data.py:239: in run_in_parallel
results = [task.result() for task in tasks]
tools/data.py:239: in <listcomp>
results = [task.result() for task in tasks]
/usr/lib64/python3.9/concurrent/futures/_base.py:446: in result
return self.__get_result()
/usr/lib64/python3.9/concurrent/futures/_base.py:391: in __get_result
raise self._exception …
```
=> scylla_node: wait_for_starting: update bootstrap message

ccmlib/common.py, tests/test_common.py
In enterprise release versions and release canidates
the the return value was `enterprise` and not one of
`release|debug|dev`
=> Fix enterprise version extraction for path/url

ccmlib/node.py, old_tests/test_lib.py
Modifies the _grep_for_log_errors function so that it matches on ERROR,
INFO and DEBUG strings only if they are a whole word, e.g. a line which
contains "ERRORS" won't be considered by the function.
My motivation behind this change is that I would like to introduce a
feature called "TYPED_ERRORS_IN_READ_RPC" in Scylla. Feature names are
printed to logs with INFO level on startup, and the current logic in
dtests (which uses the grep_log_for_errors function) considers this to
be a failure. This commit tightens the check so that the feature can be
added without problems, and lines printed with error log level (I
suppose they are of most interest here) are still matched by the logic.
=> _grep_log_for_errors: match only if ERROR, INFO, DEBUG is a whole word

ccmlib/scylla_node.py
Don't use the thrift interface since it may be changed to localhost
by tests like `pushed_notifications_test.py::TestPushedNotifications::test_restart_node_localhost`:
```
ccmlib.node.NodeError: Error starting node node1: unable to connect to scylla-jmx port localhost:7199
```
=> scylla_node: start: use storage network address for jmx host

ccmlib/node.py, ccmlib/scylla_node.py
so we can pass down parameters to the `nodetool()`
mostly timeout
=> node: pass down kwargs to node.flush() call

MANIFEST.in, ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/resources/docker/sniproxy/Dockerfile, ccmlib/scylla_cluster.py, ccmlib/utils/sni_proxy.py, ccmlib/utils/ssl_utils.py
So the different drivers can be test their new
implementations of sni-proxy
for using it, need to start the cluster from the commandline
like this:
```
❯ ccm start --sni-proxy
sni_proxy listening on: 127.0.0.1:443
```
using it from python code, would be a bit diffrent:
```python
nodes_info = get_cluster_info(self.cluster.get_path(),
address=self.cluster.nodelist()[0].address(),
port=9142)
docker_id, listen_address, listen_port = \
start_sni_proxy(self.cluster.get_path(), nodes_info=nodes_info)
```
Ref: https://github.com/scylladb/gocql/pull/97
=> Add sni-proxy support to CCM

ccmlib/utils/ssl_utils.py
when running with older versions of openssh, we were failing
like the following:
```
E       TypeError: can only concatenate list (not "str") to list
```
we should return a list, and not empty string
=> ssl_utils.py: return list and not str, on older openssh

ccmlib/common.py
In cases the `--cassandra-dir=<path-to-ent>/build/dev` was pointing
to specific build type inside the build tree, we were failing
to figure the version (since looking in the wrong directory)
most time it wasn't critical for running tests, but in case of
enterprise tests, dtest assumed it's OSS and filtered the tests
and making the test unrunable for a developer
=> ccmlib/common.py: make sure we look all directories

ccmlib/utils/ssl_utils.py
Due to language constraints java driver desperately needs the key to be in `PKCS#8` format.
I'm not fully aware if this change would break any other tool.
=> Generate key in PKCS#8 format instead of PKCS#1

ccmlib/utils/ssl_utils.py
3b6323fa9dd6eb2b1586de0d601af2d090e66a3f changed the key format
seem like it's not working as expected, adding the option
to create both keys
=> ccmlib/utils/ssl_utils.py: change back to create default rsa key

ccmlib/node.py, tests/conftest.py, tests/test_scylla_docker_cluster.py, tests/test_scylla_relocatable_cluster.py
since `stress()` was returning only stderr and stdout
`stress_object()` treated anything printed in the stderr as errors
but cassandra stress also print warning into the stderr
and `stress_object()` started accumlating all kind of strings
it should ignore.
this change align those two function to be working similar
to the code in the ccm upstream, and now `stress()` returns
a nametuple that has rc,stderr,stdout. so the user can read
the outout and parse it as it wants, if the `rc!==0` an exception
is being raised (caller should catch it, if it's expected to fail
non of the dtest use it like that)
Test: added an integration test to cover those two function
Close: #402
Ref: scylladb/scylladb#11445
=> ccmlib/node.py: refactor stress() and stress_object()

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py
Since in some cases we need to be able to download enterprise versions, and not only OSS (or in some cases both versions)
insted of counting on enviremnt variable to be set, it's now can be called explicitly
=> scylla_reporsitry: add option to pass `scylla_product` to setup()

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py
since we have a very clear versioning scheme for release
we can detect from a release version if it's enterprise or not.
we don't need any changes to dtest for that, since setting
the product by the under test product, means that we'll lock
the enterprise test from upgrading from OSS, which we do
want to keep testing.
Fixes: https://github.com/scylladb/scylla-dtest/issues/2852
=> ccmlib/scylla_repository.py: automaticlly detect releases product

ccmlib/scylla_repository.py
Since when using scylla under ccm we don't need any systemd related things, we should disabled it. (now that it's possible)
Ref: scylladb/scylladb#11345
Ref: scylladb/scylla-jmx#186
Closes: scylladb/scylla-dtest#2819
=> ccmlib/scylla_repository.py: use --without-systemd option

ccmlib/scylla_repository.py
When we are trying to download older versions (5.0 and below), the download is failing like this:
```
File "/home/fruch/.pyenv/versions/3.10.5/envs/scylla-ccm-3.10.5/bin/ccm", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/fruch/projects/scylla-ccm/ccm", line 75, in <module>
cmd.run()
File "/home/fruch/projects/scylla-ccm/ccmlib/cmds/cluster_cmds.py", line 218, in run
cluster = ScyllaCluster(self.path, self.name, install_dir=self.options.install_dir,
File "/home/fruch/projects/scylla-ccm/ccmlib/scylla_cluster.py", line 50, in __init__
super(ScyllaCluster, self).__init__(path, name, partitioner,
File "/home/fruch/projects/scylla-ccm/ccmlib/cluster.py", line 71, in __init__
dir, v = self.load_from_repository(version, verbose) …
```
=> scylla_repository: fix retriving older versions

ccmlib/node.py
Some conf files, e.g. cassandra-rackdc.properties may have already been prepared by the cluster class
(via add -> __update_topology_files ->
__update_topology_using_rackdc_properties),
and we want to keep them in case node.update_configuration_options was called after cluster.new_node for the newly added node.
=> node: copy_config_files: do not clobber existing files by default

ccmlib/cmds/cluster_cmds.py, ccmlib/common.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py, tests/test_scylla_relocatable_cluster.py, tests/test_scylla_repository.py
For a while now scylla supplies a unified package that consist of scylla, jmx, and tools. historicly ccm handle each one on it's own, and never consumed the unified package.
we now default to taking the unified package, and fallback to regular flow if we fail to retrive it's path from the metadata file `00_Build.txt`
Closes: #243
TODO:
=> feature(unified-package): support scylla unified packages

ccmlib/scylla_repository.py
code was using `--supervisor` to disable systemd checks, but this flag was introduced only in scylla 4.6
and it breaks installing older releases, for example `2021.1.16`
for other flags we check the installer version, but this specifc flag didn't come with a version change, hence we are looking for it in `install.sh`
Fixes: #413
=> ccmlib/scylla_repository.py: unified install don't unavailable arguments

ccmlib/scylla_node.py, ccmlib/scylla_repository.py
in recent fixes we added a check of the content
of `install.sh` it seems be conflicting with the change made to support `package_version==3.0` which means there a inner directory inside the tarball that
need to be leveled to align to the structure the
ccm code expects
=> fix(unified-installer): handle inner direcoty

ccmlib/utils/sni_proxy.py
Field insecureSkipTlsVerify was incorrectly put in AuthInfo instead of Datacenter. Therefore, generated .yaml config bundles were invalid.
=> Fixed yaml model (insecureSkipTlsVerify)

ccmlib/common.py, ccmlib/node.py
in dtest we should be printing anything to stdout, everything should go into the logs.
when ccm is use as standalone (via cli), those would be printed to stdout.
=> node.py: change print to logging in `run_cqlsh`

ccmlib/node.py, ccmlib/scylla_node.py
in some tests, we are using nodetool in high quentites and we don't want to fill the logs with that information (it's mostly preperation for the actul test)
see dtest `data.simulate_write_process_in_minutes`
so we are adding a way to disable the logging that was recently added to `node.nodetool`
=> node.nodetool: add verbose argument

ccmlib/scylla_node.py
Extend the regular expression in wait_for_starting
to look for more messages indicating progress of repair and off-strategy compaction that follows it
to extend the time we wait for a starting node to start listening for CQL.
=> wait_for_starting: off strategy

ccmlib/scylla_node.py
Commitlog O_DSYNC is intended to make Raft and schema writes durable in the face of power loss. To make O_DSYNC performant, we preallocate the commitlog segments, so that the commitlog writes only change file data and not file metadata (which would require the filesystem to commit its own log).
However, in tests, this causes each ScyllaDB instance to write 384MB of commitlog segments. This overloads the disks and slows everything down.
Fix this by disabling O_DSYNC (and therefore preallocation) during the tests. They can't survive power loss, and run with --unsafe-bypass-fsync anyway.
=> node.py: disable commitlog O_DSYNC, preallocation

ccmlib/scylla_node.py
Fixes #426
To smoothly use different scylla-jmx java executable w/o changing link in /usr/bin.
=> scylla_node: Allow set JAVA_HOME to override scylla-jmx link

ccmlib/scylla_node.py
Looking at https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/135/testReport/, for example, we see that many tests in `resharding_test` and `materialized_views_test.py::TestInterruptBuildProcess` fail with
```
ccmlib.node.NodeError: 30 Jan 2023 05:31:16 [node1] Missing: ['Starting listening for CQL clients']:
Scylla version 5.3.0~dev-0.20230130.84a69b6adb3d w.....
See system.log for remainder
```
This is caused by a long standing bug (introduced in c1762841eec615ba315be1b4b841aaef5108281d):
```
try:
t = timeout * 4 if timeout is not None else 420 if self.cluster.scylla_mode != 'debug' else 900
self.wait_for_binary_interface(from_mark=self.mark, process=self._process_scylla, timeout=60)
except TimeoutError as e:
if not …
```
=> scylla_node: start_scylla: fix wait for binary interface timeout path

ccmlib/cluster.py, ccmlib/node.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py, ccmlib/utils/version.py, tests/test_scylla_repository.py
since moving to using unifed package by default the retrival of release canidates were broken
=> scylla_repository.py: fix the retrival of release canidates version

ccmlib/node.py
The hostid nver changes so there no reason to
use nodetool every time to get it.
Tests that want to exercise nodetool for that can do that by explicitly running nodetool, or passing force_refresh=True if they insist :)
Otherwise, cache the result in self.node_hostid
to be reused next time hostid() is called.
This is particularly needed for node operations
scenarios when an operation like replacenode
runs after removenode that happened to stop the
to-be-replaced node.
Since scylladb/scylla-dtest@97a341adc4adeb1a27e00db1bb4614b0d1f53618 the replace node operation operates on the node hostid and that cannot be retrieved if the node is already dead without this change.
=> node: keep hostid result in self.node_hostid

ccmlib/scylla_repository.py, tests/test_scylla_repository.py
when ccm was pass `2023.1.0~rc0` it would fail like this:
```
File ".../site-packages/ccmlib/scylla_repository.py", line 136, in release_packages
raise ValueError(f"Not expected version number: {version}. S3_URL: {s3_url}")
ValueError: Not expected version number: 2023.1.0.0~rc0. S3_URL: https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2023.1
```
it was a faulty regex that wasn't behaving correctly also fix the filtering of unified packages, since the nameing changed a bit, once again
=> scylla_repository: Fix handling of full version release candidates

ccmlib/scylla_node.py
so the dtest tests are able to acess the exact number of shard used
for testing. for instance, some of them might need to calculate the
exact total memory based on this option.
=> scylla_node: expose ScyllaNode.smp()

ccmlib/common.py, ccmlib/node.py, ccmlib/scylla_repository.py, tests/test_scylla_repository.py
extend fix from https://github.com/scylladb/scylla-ccm/commit/424dd4445b6fc0c678e9505b00a0df0cdb39939b to
all `install.sh` scripts inside the unifed-package.
Fix: https://github.com/scylladb/scylla-dtest/issues/3060
=> scylla_repository: patch systemctl calls out of install.sh 

README.md
Add two examples that allow to quickly get started with `scylla-ccm`.
It took me a moment to find how to do this using `scylla-ccm`, so I think it would be good to include such examples in the README.
Fixes #438
=> README: add simple usage examples

ccmlib/scylla_repository.py
69d304 introduced change to `run()` so we can log
better the output of commands, but it failed
to raise the error after that.
that made the output a bit confusing and failed the whole idea.
=> scylla_repository: re-raise exception on `run()`

ccmlib/cmds/cluster_cmds.py, ccmlib/utils/sni_proxy.py
The `create_cloud_config` function generates files config_data.yaml and config_path.yaml. The files were created with the hardcoded datacenter name eu-west-1 which is now replaced by fetching the real datacenter name from the node's `system.local` table.
=> Replace eu-west-1 with system.local data_center value

ccmlib/scylla_node.py
We'd like to use the values provided in the SCYLLA_EXT_OPTS environment variable as defaults, but also derive
self._mem_mb_per_cpu from them.
Then, if a test passes --smp, without --memory in jvm_args we should calculate --memory from self._mem_mb_per_cpu * _smp.
Otherwise, the default --memory parameter given in SCYLLA_EXT_OPTS could be too small if the test uses more shards than the default.
See for example https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/216/artifact/logs-full.release.018/dtest-gw2.log that times out when bootstrapping new nodes with smp=8 and memory=1024M takes increasingly longer due to the immense memory pressure.
```
06:25:11,552 740     ccm                            DEBUG    cluster.py          :711  | test_lwt_load: node1: …
```
=> scylla_node: derive mem_mb_per_cpu from --smp and --memory options

tests/conftest.py, tests/test_scylla_cmds.py
since recent failure we had, adding few tests that would verify ccm is working as expcet with scylla
master latest version
=> test_scylla_cmds: test also with scylla master latest

README.md, ccm, ccmlib/cli_session.py, ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/command.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/repository.py, ccmlib/scylla_cluster.py, ccmlib/scylla_docker_cluster.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py, ccmlib/utils/__init__.py, ccmlib/utils/sni_proxy.py, ccmlib/utils/ssl_utils.py, old_tests/test_cmds.py, old_tests/test_lib.py, setup.py, tests/ccmcluster.py, tests/conftest.py, tox.ini
- setup, tox.ini: do not claim the python2.x support
- treewide: run 2to3 to the tree
- treewide: use f-string when appropriate
- treewide: do not use six module
Fixes #432
=> treewide: drop python2 support

ccmlib/scylla_node.py
there are chances that user installs the tool to be found in $PATH,
for instance, user might already install the specified tool using
`pip install scylla-cqlsh`. so we should use $PATH as a fallback
instead of assuming that they are located under the two candidate
directories.
so, in this change, in addition to the candidate directories, we
also search for the tool in $PATH, as `shutil.which()` search the
given cmd in $PATH if the specified `path` parameter is None.
=> scylla_node: find tool in $install_dir/tools/cqlsh/bin also

ccmlib/scylla_node.py
for less conditions in code, for better readability.
=> scylla_node: use '/usr' as default JAVA_HOME

ccmlib/common.py, ccmlib/node.py, tests/test_scylla_download.py, tests/test_scylla_repository.py
since we are switching to use jvm11 for scylla, but still have test that are using cassandra 3.11 that works only with jvm8, we are hardwiring the code to always try to select the jvm8 for cassandra
=> make_cassandra_env: hardcode java_home to jvm8

.github/workflows/integration-tests.yml, setup.py
Look like new version of requests is pulling newer versions of urllib3 which are not comptible with
botocore.
Ref: https://github.com/boto/botocore/issues/2926
Ref: https://github.com/psf/requests/issues/6443
Ref: https://github.com/urllib3/urllib3/issues/2168
=> pin down urllib3<2 since botocore doesn't support it

ccmlib/common.py, tests/ccmcluster.py, tests/test_scylla_cmds.py
since in some distro or jvm manager we might have more folders
in `/usr/lib/jvm/` which are just information folders with ends with
`*.jinfo` but the same as the actual folder we are looking for.
=> hardcode_java_version: add check for for existence of java binary

ccmlib/node.py
Set by default to 10 minutes to prevent blocking in `communicate` forever.
Blocked run_cqlsh was seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/244/testReport/cqlsh_tests.cqlsh_copy_tests/TestCqlshCopy/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_copy_to_with_child_process_crashing/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/244/artifact/logs-full.release.000/dtest-gw3.log
```
13:13:59,598 751     cqlsh_tests.cqlsh_copy_tests   DEBUG    cqlsh_copy_tests.py :1525 | test_copy_to_with_child_process_crashing: Exporting to csv file: /tmp/tmpqskw5279 with {"exit_range": {"start": 0, "end": 5000000000000000000}}
...
13:58:50,244 751     errors                         ERROR    conftest.py …
```
=> node: run_cqlsh: add timeout parameter

ccmlib/scylla_node.py
seem like there was a call to `node.is_running()` that wasn't checking the output, and assuming it would update the pid information, and wasn't always the case.
this was causing cases that the next node would identifed as running and not considered as part of the `wait_other_notice` check.
=> ccmlib/scylla_node: wait for scylla process to be running

ccmlib/cmds/node_cmds.py
make `versionfrombuild` command work without a running node we don't need to cross check with nodetool that the version is the correct one, the once mention in scylla package is enough for us.
we need this working for driver test that would be able to pick test base on the versions.
=> ccmlib/cmds/node_cmds: make versionfrombuild useful

ccmlib/common.py, ccmlib/scylla_node.py
remove text parameter from `wait_for` it was spamming the outout for now real reason. we should be print to stdout during tests. for debug propuses we
should be using `logging.debug`, which in
this case isn't needed.
Fixes: #465
=> ccmlib/common: remove prints from `wait_for`

ccmlib/node.py, tests/test_scylla_cmds.py
since when we want to use `-cloudconf` flag
we shouldn't be appending address and port to the
commandline arguments.
=> ccmlib/node: add support for `cassandra-stress -cloudconf`

ccmlib/common.py, ccmlib/scylla_repository.py, tests/test_common.py
Up until now the locking mechanism used to prevent concurrent downloads was just the existence of a lock file. This implementation had several problems:
- Locking procedure was unsafe - it was possible for more than one process to enter critical section at the same time. This was "fixed" by putting random sleep in front of it, but that is not a proper synchronisation mechanism.
- Download procedure was clearing whole directory at one point. This caused lockfile to be removed too, so it was possible for another process to enter the critical section at this point.
- If the process was killed unexpectedly, the lockfile remained in place. If you try to start the download again it will wait for an hour for the lockfile to be deleted. This is frustrating when running e.g. tests for some driver, …
=> Use advisory locks for lockfiles

ccmlib/common.py
* Support disabling `public` access for some buckets that we don't have public access yet
* Automaticlly sort by date the returned file list, since the users of this function only get the key names, and loses the modify date and parsing the date out of the name isn't trivial
=> ccmlib/common: improve `aws_bucket_ls`

ccmlib/scylla_repository.py, ccmlib/utils/download.py
* now it would first try to download from s3 via boto api (faster)
* local tar.gz file of manager can be used (no need to have it on s3/http)
* hash to identify the specific version now based on ETag and not on the url path itself.
Fixes: #463
=> scylla-manager: make `--scylla-manager-package` option more robust

ccmlib/scylla_repository.py, tests/test_scylla_repository.py
those helper function could be user to retrive scylla manager relocatable packages, that we need in dtest for testing manager, those comes in two flavors:
* one to retrive lastet version of of specific branches
* one to retrive specific released versions
=> ccmlib/scylla_repository: introduce get_manger_* functions

.envrc, .github/workflows/nix.yml, .gitignore, README.md, flake.lock, flake.nix
Nix is, citing their GH repo,  'a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible.'
See here for a more detailed description: https://serokell.io/blog/what-is-nix
We want to use Nix in drivers (starting with Java driver) to create reproducible, easy to use development environments, and later to extend this to CI and release process.
In order to do that, we need to create Nix package for CCM, as it's used by many drivers in integration tests. This PR accomplishes experimental version of it.
PR introduces Nix flake that can be used to add CCM as a dependency somewhere or to quickly enter a development environment where you can run and test CCM (with caveats due to Scylla using absolute paths when searching for Java - see …
=> Add experimental Nix Flake support

.github/workflows/integration-tests.yml, ccmlib/common.py
Recent change introduced typing that is incompatible with Python < 3.9. There are other Scylla projects relying on CCM (e.g. most drivers) and for some of them this change caused CI failures (as of now - for Rust driver and Python driver).
This PR fixes the problem by making this typing compatible with older Python versions.
It also adds CI that runs on older Python. I wanted it to be 3.6, because that's the oldest version supported by Python driver, but it seems this version can't be installed by `setup-python@v4` action, so I bumped it to 3.8
=> Fix Python 3.8 compatibility

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
After starting a multi-node cluster, it's important to wait until all nodes are aware that all other nodes are available, otherwise if the user sends a CL=ALL request to one node, it might not be aware that the other replicas are usable, and fail the request.
For this reason a cluster's start() has a wait_other_notice=True option, and dtests correctly use it. However, the implementation doesn't wait for the right thing... To check if node A thinks that B is available, it checks that A's log contains the message "InetAddress B is now UP". But this message is unreliable - when it is printed, A still doesn't think that B is fully available - it can still think that B is in a "joining" state for a while longer. If wait_other_notice returns at this point, and the user sends a CL=ALL request to …
=> scylla_cluster: fix handling of wait_other_notice

.envrc, .gitignore
diffrent people are using direnv diffrently
we shouldn't put it on the source
=> remove .envrc from source

ccmlib/scylla_node.py
disable `urllib3.connectionpool` logging for this function, it doing lots of retries and we don't need to see each request that is being sent out in the log
Ref: #477
=> scylla_node: disable logging for `watch_rest_for_alive`

ccmlib/common.py
we have some dtests which are marked with "dtest_enterprise" mark. and they deselect themselves if ccm claims that the scylla build is not enterprise.
sometimes, we just want to run some of these dtest right from local build, whose SCYLLA-VERSION-FILE is co-located with the scylla executable binary, right under the "install_dir" instead of "install_dir/build/" or somewhere else. so, in this case, ccm would either fail to find the right SCYLLA-VERSION-FILE, or find a wrong one.
in this change, we add $install_dir/SCYLLA-VERSION-FILE at the front of the check list, so that ccm can check and use it if this file exists. this should address the pain of developers who want to test from the local build.
=> ccmlib/common: check install_dir/SCYLLA-VERSION-FILE first

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
seems like the 360s default for debug for `watch_rest_for_alive` isn't enough as it was for `watch_log_for_alive`,
making it 600s (10min)
Fix: #477
=> scylla_cluster,scylla_node: increase debug timeout for `watch_rest_for_alive`

ccmlib/node.py
To allow specifying the keyspace/table to compact, instead of compacting all of them.
=> node.py: compact(): add keyspace and tables argument

ccmlib/scylla_node.py
`ScyllaNode.dump_sstables()` is a wrapper around
`ScyllaNode.run_scylla_sstable()`. it provides a more user friendly interface than the latter. it is introduced so that tests can use it with less pain when migrating from
`node.run_sstable2json()` to `node.run_scylla_sstable()`.
=> scylla_node: add ScyllaNode.dump_sstables()

ccmlib/node.py
After recent changes to scylla, we fount that:
* this call was failing silently
* was printing to stdout, and not into logging
exmple of such failure, that some test failed to notice:
```
[2023-07-26T06:42:39.223Z] Exception in thread "main" java.lang.NumberFormatException: For input string: "3g7z_0in1_5tmap2bezca73ozy4m"
[2023-07-26T06:42:39.224Z] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[2023-07-26T06:42:39.224Z] 	at java.base/java.lang.Integer.parseInt(Integer.java:652)
[2023-07-26T06:42:39.224Z] 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
[2023-07-26T06:42:39.224Z] 	at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:280)
[2023-07-26T06:42:39.224Z] 	at …
```
=> ccmlib/node: capture the output of sstable2json command in logging file

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
* moving the setting those default timeout into the cluster `__init__`
and a user of the cluster (i.e. dtest) can set those higher
if needed.
* removed `timeout` argument from `_start_scylla` since no
code in ccm or dtest were using it.
* reversed the order of `wait_for_binary_proto` with `wait_other_notice`
since it was agree that `wait_for_starting` should happen first
and the chances that after `wait_for_binary_proto` would end,
`wait_other_notice` could finish much faster (current assumption
is that no test is calling wait_other_notice=True while
wait_for_binary_proto=False)
=> scylla_cluster: introduce `cluster.default_wait_*` properties

ccmlib/scylla_node.py
it turns out we do have a use case in dtest where the caller of `node.run_sstable2json()` passes a single sstable to this method. so let's cater its needs.
see compaction_additional_test.py
=> scylla_node: add datafiles param to ScyllaNode.dump_sstables()

ccmlib/node.py
seems like introducing of raising failure on any failure of sstabledump has started to fail some dtests
since it was used in some places right after compation and some of the sstable were deleted between listing them to using them with sstable dump, so we need to ignore failures from non existing files.
=> ccmlib/node: run_sstable2json to handle non-exist files

ccmlib/node.py
=> ccmlib/node: avoid using too many `not` in condition expression

ccmlib/node.py
a741f782bb4c9fef33bd3c42ac3bacb9a0f1cc42 has an issue it was looking into the wrong variable to check the stderr, and when there a failure would cause the
wrong failure
fix: scylladb/scylla-dtest#3454
=> ccmlib/node: fix `run_sstable2json` on exception case

ccmlib/node.py
The following has been seen in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/247/testReport/lwt_banking_load_test/TestLWTBankingLoad/Run_Dtest_Parallel_Cloud_Machines___HeavyDtest___heavy_split000___test_bank_with_nemesis/:
```
self = <lwt_banking_load_test.TestLWTBankingLoad object at 0x7f1aeef51890>
with_oracle = True
def test_bank_with_nemesis(self, with_oracle=True):
start = time()
>       session = self.prepare()
lwt_banking_load_test.py:1122:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <lwt_banking_load_test.TestLWTBankingLoad object at 0x7f1aeef51890>
num_nodes = 4
def prepare(self, num_nodes=NODES):
"""Set up cluster, schema, tables"""
cluster = self.cluster
cluster.set_configuration_options(values={ …
```
=> node: manage all_pids as a set

ccmlib/common.py, tests/test_common.py
The current regular expression failed to match
the mode for e.g
`https://downloads.scylladb.com/unstable/scylla/master/relocatable/latest/scylla-debug-unified-5.4.0~dev-0.20230801.37b548f46365.x86_64.tar.gz`
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/247/consoleText
```
[2023-08-06T05:45:02.790Z] SCYLLA_UNIFIED_PACKAGE=/jenkins/workspace/scylla-master/dtest-debug/scylla/build/debug/dist/tar/scylla-debug-unified-5.4.0~dev-0.20230801.37b548f46365.x86_64.tar.gz
```
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/247/artifact/logs-full.debug.052/dtest-gw0.log
```
07:54:08,036 790     errors                         ERROR    conftest.py         :208  | test_cluster_expansion_with_cdc[Single_cluster]: test failed:
...
try:
> …
```
=> scylla_extract_mode: fix regex pattern to match mode

ccmlib/node.py
seems like 730e556bce9a74e2bee9f5e00ced3968e272b8db wasn't enough and it didn't handled cases command would fail and stderr is None
also seem like we are not pipeing stderr, as we should for this exception handling to work correctly.
=> ccmlib/node: fix `run_sstable2json` on exception case - yet again

ccmlib/node.py
this change enables Node.check_node_sstables_format() to match sstable component files which use uuid-based sstable identifier. this should pave the road of dtest to test with
uuid_sstable_identifiers_enabled set.
=> node: match with uuid-based sstable identifier

ccmlib/scylla_node.py
so we can have better understanding of the format when using this function.
=> scylla_node: improve the sample return val of node.dump_sstable()

ccmlib/node.py
To help understand spurious timeout error we encounter.
Refs https://github.com/scylladb/scylla-cqlsh/issues/37
=> node: run_cqlsh: dump tool's stdout and stderr on timeout

README.md
Add instructions that describe how to create a cluster of Scylla nodes with a specific build-id.
It's not obvious how to achieve this - you have to download the right package from the right place, and then use the right combination of flags for `ccm`.
Let's add the instructions to make it easier for future users of `ccm`.
=> readme: Add info on creating a build-id cluster 

ccmlib/scylla_node.py
The flush api is synchronous and so it waits for
the respective flush to get done and will return
and error if flush failed for any reason and
this will propagate through nodetool flush.
_wait_no_pending_flushes may fail if there
are spontanuous flushes, and it also tends to
timeout in nodetool cfstats in debug mode,
see for example:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/250/testReport/alternator_ttl_tests/TestAlternatorTTL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split029___test_ttl_with_load_and_decommission/
```
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:1320: in flush
self._wait_no_pending_flushes(verbose=kwargs.get('verbose', True))
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:1314: in …
```
=> scylla_node: no need to _wait_no_pending_flushes

ccmlib/node.py
see also 3616251066f8a520a7eec99d507dc16128e2926f
otherwise, `sstablelevelreset` would try to load the unsealed sstables and print out error messages in stderr if not all the components are available or is corrupted. this fails the test which checks for unexpected errors.
Fixes https://github.com/scylladb/scylladb/issues/15210
=> ccmlib/node: cleanup unsealed system sstables for offline tools

ccmlib/node.py
for enabling more of dtest need, added `env` argument to 
pass in environment variables needed for the test.
=> ccmlib/node: add `env` argument to `Node.run_cqlsh()`

ccmlib/scylla_repository.py
support of older releases unified packages
that we still need to patch the systemctl calls from taking
place
=> scylla_repository: fix installing of older unified packages

ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/common.py, tests/test_common.py
since in some place we need to be able to pass in a list
for example in `experimental_features`, ccm didn't support it
in the `ccm updateconf` command, now it would support it
but passing it via the command line, like the following:
```bash
> ccm updateconf experimental_features:[udf,tablets]
```
=> ccmlib/common: support yaml syntax in updateconf command values

ccmlib/node.py
`watch_log_for_death` scans node logs looking for a message that says `"<nodeaddress> is now DOWN"`. When this message appears in the logs of other nodes we can be certain that this particular node is now DOWN.
In `Scylla` the messages looks like this:
```bash
127.0.0.1 is now DOWN
127.0.0.1 is now UP
```
But in `Cassandra 4.1.3` the messages are a bit different:
```
127.0.0.1:7000 is now DOWN
127.0.0.1:7000 is now UP
```
In Cassandra the node's address also includes the port. `watch_log_for_death` didn't handle this properly - the regex expected an ip address and then " is now DOWN".
Because of this it wasn't able to detect the message and `node.stop()` kept timing out for Cassandra nodes.
To fix it let's generalize the regex so that it handles both of the messages properly.
The regex is …
=> node.py: generalize expected message in watch_log_for_death

ccmlib/cluster.py, ccmlib/node.py, tests/test_set_keyspace_initial_tablets.py
We want to test tablets functionality without need for test adaptation (creating keyspace with tablets enabled  before node.stress is run).
Modify `stress_options` by add `initial_tablets` option and change replication strategy to `NetworkTopologyStrategy` to support tablets tests.
fixes: https://github.com/scylladb/scylla-ccm/issues/509
=> enable tablets in kespaces created by node.stress

ccmlib/utils/sni_proxy.py
4cdf92333e6a1115dd2b20b292ee955fd5632527 was trying to apply retry of the `docker build` command
but it wasn't complete and would really retrying
Fixes: scylladb/scylladb#15662
=> utils.sni_proxy: fix docker build retry logic

ccmlib/common.py, ccmlib/scylla_cluster.py, tests/test_common.py
Commit 4f619b75ab048366f3a0f7971450d00485e910bc (scylladb/scylla-ccm#492)
Improved the regular expression used in `scylla_extract_mode` to better
detect the scylla_mode given the package url.
However, when we install from a local path, like
`/jenkins/workspace/scylla-master/dtest-debug/scylla/build/debug/dist/tar/scylla-debug-unified-5.4.0~dev-0.20231013.055f0617064d.x86_64.tar.gz`,
The regular expression fails to detect the mode since it falsely start the match at `/scylla-master`.
This change restricts the match to the last path component.
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/258/artifact/logs-full.debug.041/dtest-gw0.log
```
07:20:43,371 790     errors                         ERROR    conftest.py         :225  | …
```
=> scylla_cluster: load_from_repository: set default timeouts

ccmlib/scylla_node.py
Change a1624b5c471c8653e3855e0bfa3ea06422e95f2a added the method to class `NodeUpgrader` instead of `ScyllaNode` by mistake so it is a no-op and `test_lcs_sstable_promotion` still fails in debug mode occasionally, like
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/261/testReport/compaction_additional_test/TestLCSSSTablePromotion/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split044___test_lcs_sstable_promotion/
```
ccmlib.node.TimeoutError: Waiting for compactions timed out after 300 seconds with 26 pending tasks remaining.
```
=> scylla_node: wait_for_compactions: move override to class ScyllaNode

ccmlib/cluster.py, ccmlib/node.py
Support a `rack` member in `Node`
and allow specifying datacenter racks by extending the `nodes` parameter to `prepare` supported notations as follows:
The motivation for doing so is for adding dtests testing mult-rack topologies.
Refs https://github.com/scylladb/scylla-dtest/issues/3681
Fixes scylladb/scylla-ccm#518
=> cluster: prepare: support multi rack

ccmlib/scylla_repository.py, tests/test_scylla_repository.py
change the code to be able to scan across both OSS and enterprise location to find a release or unstable relocatable package
`SCYLLA_PRODUCT` envirment variable is still in the code but used only when fetching really old release that doesn't have unified relocatable package (ex. 2020.1), leave this code so we can still fetch and use those old versions
=> scylla_repository: remove the need of `scylla_product`

ccmlib/scylla_node.py
it was a copy-n-pasta error. and should be dump-statistics not dump-data.
=> scylla_node: correct the docstring of ScyllaNode.dump_sstable_stats()

pytest.ini
otherwise pytest complains at seeing the marker of `repo_tests`, like
```
============================================================================================================== warnings summary ==============================================================================================================
tests/test_scylla_download.py:9
/home/kefu/dev/scylla-ccm/tests/test_scylla_download.py:9: PytestUnknownMarkWarning: Unknown pytest.mark.repo_tests - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.repo_tests
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
this warning is distracting.
=> pytest.ini: s/repo_test/repo_tests/

tests/test_scylla_repository.py
it turns out the latest scylla-manager's reloc tarball's URL contains contains "-SNAPSHOT" instead of "-dev-" in it. so let's update the test to reflect the fact.
the name should match with the name specified by
scylla-manager/dist/.goreleaser.yaml 's `name_template`.
=> scylla_repository: expect -SNAPSHOT in scylla-manager reloc URL

ccmlib/scylla_node.py
this series adds
- `validate_sstable()`
- `validate_checksums_sstable()` 
helpers to `ScyllaNode`
=> ccmlib/scylla_node: add validate_sstable() and validate_checksums_sstable() helpers

ccmlib/scylla_node.py
We'd like to deprecate collectd, we use Prometheus these days. 
Refs: https://github.com/scylladb/scylla-enterprise/issues/3628
=> Remove --collectd-hostname from node command line invocation

ccmlib/node.py, ccmlib/scylla_node.py
before this change, wait_for_compactions() waits until all pending compactions are finished. but sometimes, we just want to
1. disable a certain $ks.$cf with column_family/autocompaction RESTful API, and
2. wait until all pending compaction tasks of the specified $ks.$cf is done, then
3. check the sstables of that table
column_family/autocompaction does not stop all compaction jobs a scylla instance, it just stops the specified table. so there are chances that we are still observing compaction tasks even if all the compactions of the specified table are stopped.
so, in this change, to cater the needs of the use case above, we add optional parameters to Node and ScyllaNode, so that we can specify the table we are interested in, instead of waiting for all tables.
also, instead of assigning …
=> ccmlib/scylla_node: add ks, cf params to wait_for_compactions()

ccmlib/node.py
intermediate command used, should be using kwargs as is since it can cause a conflict in parameters.
=> ccmlib/node: handle using stdout or stderr

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
It is not enough for node to know about other nodes' tokens, as they might not be reflected in the token_metadata map.
Instead, check the `/storage_service/host_id` api that provides a list of nodes that are normal token owners and ready to be used by queries.
Refs https://github.com/scylladb/scylladb/issues/15146
=> scylla_node: watch_rest_for_alive: wait for others to be considered normal token owners

ccmlib/node.py
Some resharding_test dtest, e.g. `test_resharding_counter` fails locally for me:
```
def _run_stress(self, op_cnt, stress_cmd):
res = self.node.stress_object(stress_cmd)
if not isinstance(res, dict):
raise Exception('Error running cassandra-stress: {}'.format(res))
assert res['total errors'] == 0
>       assert res['total partitions'] >= op_cnt
E       assert 10.0 >= 10000
```
When printing the cassandra-stress stdout I saw that it uses a comma as a 1000s separator:
```
Total partitions          :     10,000 [COUNTER_READ: 10,000]
```
This is probably related to the LOCALE on my machine.
This change explicitly sets the locale to en_US
tha defines comma as the thousands separator
and dot as the decimal point.
The origin local is reset when the function is done.
=> node: stress_object: strip off commas from value strings

ccmlib/scylla_node.py
If `scylla sstable` fails, the standard printouts for `subprocess.CalledProcessError` are insufficient to determine what went wrong.
=> scylla_node: run_scylla_sstable: print stderr on failure

ccmlib/node.py, tests/test_internal_functions.py
`nodetool compactionstats` may contain more lines after the pending tasks section.
For exameple:
```
pending tasks: 2
- system_schema.tables: 1
- system_schema.columns: 1
id                                   compaction type keyspace      table   completed total unit progress
8e1f2d90-a252-11ee-a7f4-1bf9ae4e6ffd COMPACTION      system_schema columns 1         640   keys 0.16%
Active compaction remaining time :        n/a
```
Break from the `_parse_pending_tasks` loop once the tail_pattern regex mismatches the line to prevent the following error, as seen for example in https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/270/testReport/resharding_test/TestReshardingTombstonesSingleNode/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_disable_tombstone_removal_du …
=> node: _parse_pending_tasks: handle tail_pattern mismatch

.github/workflows/integration-tests.yml, README.md, ccmlib/repository.py, ccmlib/scylla_cluster.py, ccmlib/utils/sni_proxy.py, ccmlib/utils/version.py, tests/test_config.py, tests/test_utils_version.py
This change removes all uses of distutils modules and replaces them with
either direct replacements or extractions from the library.
LooseVersion is extracted into ccmlib.utils.version and dir_util.copy_tree
is replaced by shutil.copytree.
Fixes #537
=> ccmlib: Remove usages of distutils

ccmlib/node.py, ccmlib/scylla_docker_cluster.py, ccmlib/scylla_node.py
Reverts scylladb/scylla-ccm#536
according to Piotr Grabowski
> This change breaks Java Driver 4.x CI with Cassandra 4.x - in one test node bootstrap starts timing out and now requires a very large timeout (120 seconds)
so revert the offending change.
=> Revert "ccmlib: stop passing auto_bootstrap"

ccmlib/cluster.py
To be used after replacing nodes.
We cannot add the replacing nodes to seeds right away since it's considered invalid to add a replacing node as a seed (probably for historical reasons).
So we need to add it only after it's finished
replace bootstrapping.
=> cluster: add add_seed method

ccmlib/scylla_node.py
instead of chaining replace() and split(), let's just use split(). simpler and more readable this way
=> scylla_node: use str.split('=') when appropriate

ccmlib/common.py
cmake generates scylla at paths like `build/Debug/scylla` instead of
`build/debug/scylla`, so check for them as well.
=> ccmlib/common: check for scylla built with CMake as well 

ccmlib/scylla_node.py
if there are no sstables, and we expect bytes as the output, we should encode the encoded json into bytes before returning it. otherwise we'd have exception like:
```
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```
when trying to decode the returned stdout.
=> scylla_node: encode stdout and stderr if not text

ccmlib/scylla_node.py
in cases there are failure in dtest runs, those print was going to stdout, which is hard to track, and might not be save at all in when using `pytest-xdist`
=> scylla_node: print `check_socket_available` failure to log

ccmlib/scylla_node.py
this pass the setting of "api_port" to nodetool-wrapper, so that it can override the "-p" option with the port number. otherwise "scylla nodetool" would not be able to access the API service by connecting to the JMX server.
=> scylla_node: pass -Dcom.scylladb.apiPort=10000 when running nodetool

ccmlib/scylla_node.py
Nodetool commands can contain a `--` sequence, after which all subsequent command line parameters are considered positional. This means that the option we are trying to add, -Dcom.scylladb.apiPort=10000, will be parsed as a positional args and will likely trigger failure in parsing the command-line arguments.
Instead of appending it to the command string, prepend it. At this point, the `cmd` starts with the nodetool command and `node.py::nodetool()` will prepend host and port args. Do the same and prepend the rest api port.
Tested locally with a test which fails with the previous code.
=> ccmlib/scylla_node.py: nodetool(): prepend api-port instead of append

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
https://github.com/scylladb/scylla-ccm/pull/462 introduced watch_rest_for_alive that replaced the calls to watch_log_for_alive on the scylla node(s) start path.
But a node is killed and then restarted, and other nodes miss the kill event, `watch_rest_for_alive` will consider that node already as up as seen by the other nodes, while previously, watch_log_for_alive, waited until other nodes discovered this node as up again, based on markes taken right before (re)starting that node.
This change brings this call back.
Fixes scylladb/scylla-ccm#563
=> scylla_cluster, scylla_node: watch_log_for_alive before watch_rest_for_alive

.github/workflows/nix.yml
encode RELOC_VERSION in the key of binary, so we can use different binary for testing. there is chance that newer ccm would like to use newer scylla executables for testing.
this series is more a refactory, and it does not change the version of scylla we are using, but in a follow up change, we will use a different `RELOC_VERSION` for testing newer scylla.
=> github/workflows/nix: extract RELOC_VERSION as an env variable

.github/workflows/nix.yml
this change addresses a regression introduced by 92494911.
in 92494911, we tried to set `$SCYLLA_VERSION` with `env.RELOC_VERSION`, but github action does not allow this. because the env variables in github's workflow YAML are expanded when the YAML file is parsed. so `SCYLLA_VERSION` is never expanded with the value of `RELOC_VERSION`.
so, in this change, to avoid the repeatings, we use environmental file to store `SCYLLA_VERSION`, so that it can be picked by the steps that consume this env var.
see also https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
=> github/workflows/nix: do not set env var with another env var

.github/workflows/integration-tests.yml
encode `RELOC_VERSION` in the key of binary, so we can use different binary for testing. there is chance that newer ccm would like to use newer scylla executables for testing.
this series is more a refactory, and it does not change the version of scylla we are using, but in a follow up change, we will use a different `RELOC_VERSION` for testing newer scylla.
=> github/workflows/integration-tests: extract RELOC_VERSION as an env variable

ccmlib/node.py, ccmlib/scylla_node.py
Soon the jmx package will be dropped from the unified package, and the scylla.git repo. Prepare for this:
* Add `use_jmx` property, based on probing the reloc package for the presence of the `jmx` directory, or the `tools/jmx` directory in the scylla repo.
* Use this new property to fence off jmx-related code. nodetool() now routes to the native nodetool directly, when use_jmx == False.
Fixes: https://github.com/scylladb/scylla-dtest/issues/4093
=> scylla-node: prepare for the post-jmx world

README.md, ccmlib/cluster.py, ccmlib/cmds/cluster_cmds.py, ccmlib/cmds/node_cmds.py, ccmlib/dse_cluster.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_docker_cluster.py, ccmlib/scylla_node.py
cassandra-cli was removed in Cassandra 2.2.0. and it was replaced by
cqlsh in newer releases. actually, scylla-tools does not build or
package this command line tool at all. so let's drop the related helpers
for accessing this tool. 
thrift was deprecated in both ScyllaDB and Cassandra. so there is
no need to pass it around. to be compatible with existing users of
the ccmlib, the thrift related parameters are preserved in public
intefaces, but they are not passed down anymore. in some places,
we enforce that the host on which thrift protocol is served should
be identical to that of binary. and actually, scylla always use
the same host address for both thrift and binary protocols. so we
replace the address like `self.network_interfaces['thrift'][0]`
with …
=> ccmlib: drop cassandra-cli and thrift support

ccmlib/scylla_node.py
in b18f85d7, we use the native nodetool if JMX is not available, but when running dtest from the local build, the jmx repo is still around, so the java-based nodetool is picked. but the java-based nodetool does not support tablets, and it would be great to always test the native implementation built locally when testing using dtest without building a relocatable package.
so, in this change, we go a step further by checking if the command line of `scylla nodetool help` works, if it succeeds, we go ahead and use `scylla nodetool`, otherwise, we fall back to the java-based nodetool. we could instead use `scylla nodetool --help` instead of calling a certain command of nodetool, but seastar returns 1 if `--help` is used. a pull request was created to address it . see …
=> ccmlib/scylla_node.py: use native scylla nodetool when it's available

.github/workflows/ci-tests.yml, .github/workflows/integration-tests.yml, .github/workflows/nix.yml
instead of repeating the RELOC_VERSION in two different workflows, let's extract it into a workflow which will drive the existing two workflow and feed them with the RELOC_VERSION.
=> github/workflows: extract RELOC_VERSION into a workflow

ccmlib/scylla_node.py
in some cases the output of `scylla sstable` can be with illegal utf-8, we should just skip them, and it would work as expected.
=> ccmlib/scylla_node: dump_sstable_stats to handle broken utf-8

ccmlib/cmds/cluster_cmds.py
It's implementation was already removed in https://github.com/scylladb/scylla-ccm/commit/06a2adf303c292239b9a84b6a674824e0204797c , but the command was still present in the list, causing an error when printing ccm's help.
=> Remove cli cluster command

ccmlib/common.py, ccmlib/scylla_node.py
when we start, for instance, a scylla node, we use `check_socket_available()` to see if the given address can be bound, if not an exception is raised. but we still have no idea who is listening on this address.
in this change, we print out the process in this case, so that we can understand the problem better. in general, it's either an infra issue, or, it could be caused by a buggy test.
=> ccmlib/common: print out process if it's listen given address

ccmlib/scylla_node.py
before this change, we are using an unreachable hyperlink in the docstring.
after this change, the unreachable hyperlink is replaced with a reachable one.
=> ccmlib/scylla_node: use reachable link

ccmlib/node.py
Currently, when watch_log_for reaches end-of-file
it sleeps for 10 milliseconds (0.01 seconds).
This proved to be too much as the caller sometimes needs to quickly react to certain log messages, and missing the event in 10 milliseconds will be too late, as seen in https://github.com/scylladb/scylla-dtest/pull/4393#issuecomment-2148934115
This change reduces the sleep time to a single millisecond and also changes the timeout detection to using a proper time-based deadline, rather than counting the number of times we sleep (I'm really not sure why it was originally done that way).
=> node: watch_log_for: reduce polling sleep time

ccmlib/utils/version.py, tests/test_utils_version.py
so that we can compare a given ComparableScyllaVersion by its major version, minor version or patch version, when we are interested in features introduced at different major version, minor version, or a certain patch version.
=> ComparableScyllaVersion: improve matching 

ccmlib/common.py, tests/test_scylla_relocatable_cluster.py
this function need to get the install_dir, and out of it it can extract the default scylla.yaml (i.e. before any modification that ccm would be doing to it)
Closes: #582
=> ccmlib/common: add function to get the default scylla.yaml

ccmlib/scylla_repository.py
- group the conditions with parenthesis for better readability.
- and move the related comment closer to the corresponding match statement.
this change trades the conciseness for better readability.
=> ccmlib/scylla_repository: add parenthesis for better readability

ccmlib/node.py
`Node.clear(only_data=True)` shall clear user defined keyspaces only leaving all system ones untouched. The patch skips all system* keyspace directories when clearing user data.
Keyspace directories contain table directories not files that shall be deleted. When clearing keyspace directories, all underlying table directories are removed.
=> node.py: Fix Node.clear(only_data=True) deleting data files

ccmlib/cluster.py
Make Cluster.populate() work correctly for option 3.b of the nodes argument (e.g., {"dc1": [2, 2]}): as described in the comment it'll be converted to something like {"dc1": {"RAC1": 2, "RAC2": 2}}
=> ccmlib/cluster: fix automatic rack naming

tests/test_scylla_repository.py
none of the version under master folder has splitted packages only i.e. all of them has unified package, hence this test isn't relevent anymore
recently we fixed the unified package retrival and miss the fact this test, got broken.
next step would be to remove the support of splitted packages completly
=> test_scylla_repository: skip test for splitted packages

ccmlib/scylla_repository.py, tests/test_scylla_repository.py
This series adds support for specifying debug mode for scylla_version.
```
flags can be added to the version using [(flag(=value)?)+]
- supported flags are:
- product=(scylla|scylla-enterprise)
- arch=(x86_64|aarch64)
- debug
```
Fixes #590
=> scylla_repository: setup: add support for debug mode

README.md, ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/common.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_docker_cluster.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py, ccmlib/utils/sni_proxy.py, flake.lock, flake.nix, setup.py, tests/test_common.py
since ruamel.yaml can preserve yaml comment
so we can have the original yaml files
of scylla
=> switch to use ruamel.yaml

ccmlib/scylla_node.py
servel place in the code were assuming that `api_port` would be 10000.
some tests in the java-driver we setting `api_port` to a random port hence breaking some of the ccm functionality, like nodetool and wait_for_other_notice logic
=> ccmlib/scylla_node: stop hardcoding `api_port`

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/common.py, ccmlib/dse_node.py, ccmlib/node.py, ccmlib/scylla_cluster.py, ccmlib/scylla_docker_cluster.py, ccmlib/scylla_node.py, ccmlib/scylla_repository.py, ccmlib/utils/sni_proxy.py
we have multiple tests failing with the following:
```
>       self.stream.write(data)
E       ValueError: I/O operation on closed file.
../scylla/.local/lib/python3.12/site-packages/ruamel/yaml/emitter.py:1249: ValueError
```
seems like it start when we have calls from multiple thread that might be
updating the same files, or sharing the same state.
this change make sure we create `YAML` instances as needed,
so they won't be shared between threads
Ref: https://sourceforge.net/p/ruamel-yaml/tickets/367/
=> treewide: make sure we use ruamel.yaml in a thread safe manner

ccmlib/scylla_repository.py
offical manager relocatable packgaes, has dropped the hash id and we need to fix the regex to not fail on those new packages names
=> ccmlib/scylla_repository: change manager package names

ccmlib/scylla_repository.py, tests/test_scylla_repository.py
Add support for optional [:debug] flag following the version string to specify debug mode.
Closes: #590
Follow-up on: #591, simple version of that. Just check for the debug flag, and if it exists, add "-debug" where appropiate.
Tested locally
```
➜ pytest -s --scylla-version='unstable/master:latest:debug' --tablets  materialized_views_test.py::TestMaterializedViews::test_do_not_finish_view_building_with_hints
S3 download: scylla-debug-unified-6.2.0~dev-0.20240816.afee3924b3dc.x86_64.tar.gz100%|██████████| 245M/245M [00:11<00:00, 21.7MB/s]
Extracting /tmp/ccm-nfwvr5ro.tar.gz (http://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/master/relocatable/2024-08-16T01:33:28Z/scylla-debug-unified-6.2.0~dev-0.20240816.afee3924b3dc.x86_64.tar.gz, /tmp/tmprl4krzl2) as version …
```
=> scylla_repository: setup: allow debug in version string

setup.py
instead of testing on 3.3 or 3.4, we test on 3.8, 3.9, 3.11 and 3.12. so update setup.py to reflect this fact.
=> setup.py: do not claim the support for 3.3 and 3.4

ccmlib/common.py
Removes cygwin support from `get_stress_bin`
(It used access unassigned variable `path` in certain case)
=> ccmlib/common.py: remove cygwin code from `get_stress_bin`

tests/ccmcluster.py
It could fail with following error:
```
def parse_cluster_status(self, stdout):
"""
Output:
Cluster: 'CCMCluster-reloc'
---------------------------
node1: UP
return:
[(node1, UP)]
"""
nodes_status = []
for line in stdout.split("\n")[2:]:
>           node, status = line.split(":")
E           ValueError: not enough values to unpack (expected 2, got 1)
```
=> tests/ccmcluster.py: make parse_cluster_status ignore lines that does not match

.github/workflows/integration-tests.yml, .github/workflows/nix.yml
actions/upload-artifact@v2 is deprecated and can't be used anymore
=> github actions: update to actions/upload-artifact@v4

.gitignore, ccmlib/common.py, ccmlib/test_common.py
Before this commit `make_cassandra_env` would only find java at
`/usr/lib/jvm/*` directory and could have misconstrue
`java-18-openjdk-amd64` as `java-8`.
This commit makes `make_cassandra_env` to look at any directory under `/usr/lib/jvm` and
to read version from java output
=> ccmlib/common.py: make java lookup logic more comprehensive

ccmlib/node.py, tests/test_internal_functions.py
Currently, when using `wait_for_compactions`, only pending tasks are considered. If there are active compaction tasks, the function will return anyway and this causes flakyness in tests, as sometimes the active task finishes before the next operation, but sometimes it doesn't.
- Rename Node._parse_pending_tasks to Node._parse_tasks
- Count all tasks, pending and active
- Allow searching for tasks based on only keyspace
- Update and refactor test to allow more varied cases
closes: #610 
refs: https://github.com/scylladb/scylla-dtest/issues/4702
=> ccmlib/node: check both pending and active tasks when waiting for compactions

ccmlib/node.py, tests/test_internal_functions.py
Currently, when using `wait_for_compactions`, only pending tasks are considered. If there are active compaction tasks, the function will return anyway and this causes flakyness in tests, as sometimes the active task finishes before the next operation, but sometimes it doesn't.
- Rename Node._parse_pending_tasks to Node._parse_tasks
- Count all tasks, pending and active
- Allow searching for tasks based on only keyspace
- Update and refactor test to allow more varied cases
closes: #610 
refs: https://github.com/scylladb/scylla-dtest/issues/4702
cherry-picked ee7ebefe86b18ee2de91d700cd54f145e8dde8e1^..4b1ac161a6212d6f6a5bc0adfe755482e3a55d33
=> [Backport 2024.2] ccmlib/node: check both pending and active tasks when waiting for compactions

ccmlib/node.py, tests/test_internal_functions.py
Currently, when using `wait_for_compactions`, only pending tasks are considered. If there are active compaction tasks, the function will return anyway and this causes flakyness in tests, as sometimes the active task finishes before the next operation, but sometimes it doesn't.
- Rename Node._parse_pending_tasks to Node._parse_tasks
- Count all tasks, pending and active
- Allow searching for tasks based on only keyspace
- Update and refactor test to allow more varied cases
closes: #610 
refs: https://github.com/scylladb/scylla-dtest/issues/4702
cherry-picked ee7ebefe86b18ee2de91d700cd54f145e8dde8e1^..4b1ac161a6212d6f6a5bc0adfe755482e3a55d33
=> [Backport 6.2] ccmlib/node: check both pending and active tasks when waiting for compactions

.github/workflows/integration-tests.yml, .github/workflows/nix.yml, ccmlib/node.py, tests/test_internal_functions.py
Currently, when using `wait_for_compactions`, only pending tasks are considered. If there are active compaction tasks, the function will return anyway and this causes flakyness in tests, as sometimes the active task finishes before the next operation, but sometimes it doesn't.
- Rename Node._parse_pending_tasks to Node._parse_tasks
- Count all tasks, pending and active
- Allow searching for tasks based on only keyspace
- Update and refactor test to allow more varied cases
closes: #610 
refs: https://github.com/scylladb/scylla-dtest/issues/4702
cherry-picked ee7ebefe86b18ee2de91d700cd54f145e8dde8e1^..4b1ac161a6212d6f6a5bc0adfe755482e3a55d33
=> [Backport 2024.1] ccmlib/node: check both pending and active tasks when waiting for compactions

ccmlib/scylla_node.py
before this change, in `ScyllaNode.copy_config_files()`we always try to copy the jvm settings packaged by scylla-tools-java package, but we plan to drop this package. but if that package is installed, `get_tools_java_dir()` would return `None`. this breaks `copy_config_files()`, like:
```
21:44:43  Traceback (most recent call last):
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/bin/ccm", line 74, in <module>
21:44:43      cmd.run()
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cmds/cluster_cmds.py", line 269, in run
21:44:43      cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat) …
```
=> scylla_node: ignore scylla-tools config files if scylla-tools is missing

ccmlib/scylla_node.py
This PR implements the `run_scylla_types` method in the ScyllaNode class
to run the `types` tool. Also added a new class, ScyllaKeyType to allow
callers to define the key type that is being sent to the types tool.
This is required by scylladb/scylla-dtest#5093 to deduce shards of the
partition keys.
Refs scylladb/scylladb#18011
=> scylla_node: add support to run `scylla types` tool

ccmlib/scylla_cluster.py
With more nodes in cluster, it may take longer for the manager to start. Existing tests confirm this observation - for 6-nodes cluster, from time to time, Manager fails to start HTTP server in 3 minutes.
Manager log for one of the tests with multiDC cluster (6 nodes in total):
```
{"L":"INFO","T":"2024-11-04T12:44:22.691+0100","M":"Scylla Manager Server","version":"3.4.0-dev-0.20241009.4c1407684-SNAPSHOT","pid":508024,"_trace_id":"QtH-7NtpRhqE5gdiayQw4w"}**
{"L":"INFO","T":"2024-11-04T12:44:24.426+0100","M":"Using config","c":{"HTTP":"127.0.28.1:5080","HTTPS":"","TLSVersion":"TLSv1.2","TLSCertFile":"","TLSKeyFile":"","TLSCAFile":"","Prometheus":"127.0.28.1:56091","Debug":"127.0.28.1:5611","ClientCacheTimeout":900000000000,"Logger":{"mode":"stderr","level":"info","sampling":null,"encoding": …
```
=> fix(manager): extend HTTP server waiting timeout for >=6 nodes cluster

.github/workflows/nix.yml, ccmlib/scylla_repository.py, pytest.ini
taking care about warnings around unsafe usage of the built-in tarlib
=> scylla_repository.py: attend to python 3.12 related warnings

.github/workflows/ci-tests.yml, .github/workflows/integration-tests.yml, .github/workflows/nix.yml, flake.nix, tests/test_config.py, tests/test_scylla_relocatable_cluster.py, tests/test_scylla_repository.py
* Updates Scylla version to `2025-01-19T09:39:05Z`
* Affects both workflows and tests 
* Update `test_get_default_scylla_yaml` to fetch different variable, `consistent_cluster_management` is no longer in default config
* Update to Java 11
* `2025-01-19T09:39:05Z` does not work with Java 8
* Fix `test_config` getting SCYLLA_VERSION from env
* Tests have hardcoded version
* Fix version specification for 2024.2
* We cannot expect `2024.2.0` as newer releases are already out
=> Update and fix workflows and tests

ccmlib/scylla_node.py
With f3cbb1d, `_get_environ` accesses self._launch_env assuming it is always initialized.
However, `_get_environ` is called indirectly from the superclass: None.__init__ function, via `import_bin_files()`.
=> scylla_node: __init__: initialize _launch_env early

.gitignore, ccmlib/scylla_repository.py
Fixes: https://github.com/scylladb/scylla-ccm/issues/638
The problem is well described in the linked issue. TLDR, it looks like we dropped "scylla-enterprise-" prefix for 2025.x relocatables. New prefix is "scylla-" (as for previous open source versions).
=> Fix fetching scylla 2025.x relocatables

ccmlib/utils/sni_proxy.py
since when we are working inside podman we can't mount /tmp and we need the exact same direcorty mount as host for sni_proxy to work as expected
=> sni_proxy.py: add option to select the temp directory used

.github/workflows/trigger_jenkins.yaml
This action will help preventing next-trigger for running every 15 minutes looking for changes. We'll trigger next gating directly on push for next* branches.
Fixes: scylladb#636
=> Trigger next gating using github action

.github/workflows/ci-tests.yml
no that we moved to not working with next in CCM,
PRs to master should start running the CI
=> .github/workflows/ci-tests.yml: start CI on PRs to master

ccmlib/cluster.py, ccmlib/node.py
Provision multi DC cluster and list `initial_token`:
```
rm -rf ~/.ccm/test
ccm create test -i 127.0.0. -n 4:0 -v release:6.2 --scylla
cat ~/.ccm/test/*/node.conf | grep init
initial_token: -9223372036854775808
initial_token: -9223372036854775708
```
As you can see only two nodes got `initial_token`
To fix that we need to pass `node_locations` to `balanced_tokens_across_dcs` And have ti fixed a bit.
After the fix:
```
rm -rf ~/.ccm/test
ccm create test -i 127.0.0. -n 4:0 -v release:6.2 --scylla
cat ~/.ccm/test/*/node.conf | grep init
Current cluster is now: test
initial_token: -9223372036854775808
initial_token: -4611686018427387904
initial_token: 0
initial_token: 4611686018427387904
```
Fixes: https://github.com/scylladb/scylla-ccm/issues/642
=> Fix multi DC token calculation

ccmlib/node.py, ccmlib/scylla_node.py
Moving ScyllaDB to host ids changes some output to use ids instead of ips. Prepare for that by checking for both.
=> Prepare for ScyllaDB move to host ids instead of ips

ccmlib/scylla_node.py
New parameter --rf-rack-valid-keyspaces cause scylla start failing for node with scylla versions 6.2, 2024.x. This cause upgrade tests from these version to failed at the begining.
The parameter --rf-rack-valid-keyspaces mostly passed via env parameter SCYLLA_EXT_OPTS for dtest runs.
Remove such parameter from the env variable before node start if scylla version on node is <2025.1
=> fix(scyll_node.start): remove unsupported parameter for old version

ccmlib/node.py
Rack is not preserved in node.conf.
As result, next call of `__update_topology_files` overwrites rack information and all nodes dropped to rack1
=> Store node rack in node.conf

ccmlib/node.py
`host-id` requires API to be up and running, which is not always the case right away.
Ignoring it there will help to reduce chance of having host-id reading error while node is starting.
Fixes: https://github.com/scylladb/scylla-ccm/issues/646
=> Do not read host-id on watch_log_for_alive

.github/workflows/nix.yml, flake.nix
When trying to update my CCM installation I noticed that it no longer builds :(
This is because buildPythonApplication looks for setup.py by default, whichwas replaced by pyproject.toml.
The fix is simple according to NixOs wiki: https://nixos.wiki/wiki/Packaging/Python#Fix_Missing_setup.py , we just need to add `format = "pyproject";`
I also added a step to CI that verifies if installation works, to prevent such issues in the future.
=> Fix Nix build failing because lack of setup.py

ccmlib/cmds/node_cmds.py, tests/test_help.py
This command implementation was previosuly removed in commit [06a2adf303c292239b9a84b6a674824e0204797c](https://github.com/scylladb/scylla-ccm/commit/06a2adf303c292239b9a84b6a674824e0204797c)
Unfortunately this commit did not remove the command from the command list, which caused "--help" to error out, and not print some other commands.
I also added a test to prevent such errors in the future.
=> node_cmds.py: Remove cli command from the list

ccmlib/scylla_cluster.py, ccmlib/scylla_node.py
Since https://github.com/scylladb/scylladb/pull/22905 nodetool repair
repairs only vnode keyspaces. To repair tablet keyspaces, you need
to use nodetool cluster repair.
Add ScyllaNode::repair that uses the appropriate nodetool command
to repair specified tables. ScyllaNode::repair method gets repair
parameters as arguments. It creates objects of newly added
{Tablet,Vnode}RepairOptions classes to serialize the params.
=> Modify Node::repair method for nodetool cluster repair

ccmlib/cluster.py, ccmlib/cluster_factory.py, ccmlib/scylla_node.py
Two changes:
1. Handle empty `ipprefix` properly
2. Load `ipprefix` from cluster config
Problem:
ip_prefix is not preserved between ccm calls.
It breaks following case:
```
ccm remove test-ccm-bug                                            
ccm create --scylla -n 1:0 -i 127.0.1. -v release:6.2 -b test-ccm-bug
ccm start --wait-other-notice --wait-for-binary-proto --jvm_arg=--skip-wait-for-gossip-to-settle=0
ccm add -b -j 7200 -r 2200 --scylla node2
ccm node2 start --wait-other-notice --wait-for-binary-proto --jvm_arg=--skip-wait-for-gossip-to-settle=0
```
```
➜  ~ cat ~/.ccm/test-ccm-bug/node*/conf/scylla.yaml| grep 'listen_address:'
listen_address: 127.0.1.1
listen_address: 127.0.0.2
```
While it should be:
```
➜  ~ cat ~/.ccm/test-ccm-bug/node*/conf/scylla.yaml| grep 'listen_address:' …
```
=> Preserve ipprefix in cluster.conf

ccmlib/scylla_cluster.py
Currently, ScyllaCluster::repair checks whether the nodetool cluster repair operation is supported by nodetool using ScyllaCluster::nodetool. However the method does not return the nodetool output.
Use ScyllaNode::nodetool in ScyllaCluster::repair.
=> scylla_cluster: run nodetool on a node

.github/workflows/integration-tests.yml, ccmlib/repository.py, ccmlib/scylla_repository.py, pyproject.toml, tests/test_scylla_repository.py
so we won't hit s3 urls on each start of a test (cause of multiple calls to `scylla_repository.setup()`)
we gonna cache this call for the time of the test session
on a new test session, those would be called only once
=> scylla_repository: cache setups

pyproject.toml
this pinning isn't needed, and boto/botocore#2926 is fixed long long ago, removing the pinning
Fixes: scylladb/scylla-ccm#454
=> Remove pinning from urllib3
