scylladb/scylla-ccm

- ccmlib/scylla_node.py
Set the number of shards the node will use. Ignore --smp passed from the
cmdline if node.set_smp() is called.
This function is useful for tests that need cluster with nodes with
different shard count.
> ScyllaNode: Add node.set_smp()

- ccmlib/scylla_node.py
> Name scylla executable correctly when using SCYLLA_DBUILD_SO_DIR

- ccmlib/scylla_node.py
ScyllaNode._mem_mb_per_cpu holds the memory size per cpu
for the node in MB (default 512).
Use self._mem_mb_per_cpu * self.smp to calculate --memory parameter,
if not given otherwise.
Add ScyllaNode.set_mem_mb_per_cpu() to set this parameter.
Ref scylladb/scylla-dtest#1006
> scylla_node: add _mem_mb_per_cpu

- ccmlib/scylla_node.py
since I'm trying to use python in python-driver-matrix, I've run into a few python3 issues
> python3 related fixes

- ccmlib/node.py
Fixes #171
This reverts commit 1545f3e412dec122c4d97044b162de9a53edbdbf.
> Revert "Use IPs instead of localhost for nodetool commands"

- ccmlib/scylla_node.py
copy and patchelf scylla if SCYLLA_DBUILD_SO_DIR is given
then run it natively, not via a shell script (`scylla.sh`), setting `LD_LIBRARY_PATH="$SCYLLA_DBUILD_SO_DIR"` in the environment
Fixes #182
Test: [byo/635](https://jenkins.scylladb.com/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/635/)
> Make dbuild scylla core dumps debuggable again

- ccmlib/scylla_cluster.py
- ccmlib/scylla_node.py
of the manager and the manager agents
> Set the prometheus port

- ccmlib/scylla_node.py
so it writes the value of AWS_S3_ENDPOINT to the file, allowing us the option to alter the endpoint of the backup process of the manager
> Modified the manager agent yaml creation

- ccmlib/scylla_node.py
Allow passing extra environment variables for running scylla.
Those are represented in a single string comprised of one or more
pairs of "var=value" separated by either space or semicolon (';')
The planned use case is for setting the environment for ASAN
to dump core on error when running dtest in debug mode.
Refs https://github.com/scylladb/scylla-dtest/issues/1186
> scylla_node: support SCYLLA_EXT_ENV

- ccmlib/node.py
Currently the usage of log marker is quite messy:
- `grep_log` does not support optional from_mark parameter, like other similar functions.
- `grep_log_for_errors` considers only self.error_mark, if set via `mark_log_for_errors`.
- Other similar methods: watch_log_for and those who call it support optional from_mark parameter.
This change unifies the handling of log marker, so that all realted methods accept
and option `from_mark` parameter and consider it if set.
In addition grep_log_for_errors still considers also self.error_mark, if set.
> ccmlib/node: grep_log, grep_log_for_errors: add optional from_mark parameter

- ccmlib/scylla_cluster.py
- ccmlib/scylla_node.py
that cause failures since build #769 of mermaid master
> Removed unnecessary configuration from the manager and agent installation

- ccmlib/scylla_node.py
Narrow down the set of errors we accept for retry so that
any other error will throw and become visible.
Refs #223
> ccmlib/scylla_node: _wait_java_up: refine error handling

- ccmlib/scylla_node.py
_start_scylla with `wait_for_binary_proto=True` may timeout
in debug mode when a node bootstraps with repair-based bootstrap.
Tolerate that by tracking `repair - Repair \d+ out of \d+ ranges`
log messages, to wait while reapir makes progress.
Allow 120 seconds of inactivity.
Tested with materialized_views_test.py:TestMaterializedViews.mv_populating_from_existing_data_during_node_decommission_test in debug mode
> ccmlib/scylla_node: _start_scylla: wait for repair

- ccmlib/scylla_node.py
> fix(scylla_manager): Added a provider to the agent's s3 config

- ccmlib/scylla_node.py
since in ccm we listen of specific address, we need to make sure
alternator is listening on the same address
> Support enabling alternator

- ccmlib/node.py
To cleanup temporary, unsealed SSTables.
Fixes https://github.com/scylladb/scylla/issues/6211
> node: get_sstables: cleanup unsealed sstables

- ccmlib/scylla_repository.py
Since we modified relocatable package structure, scylla-ccm need to
detect and handle different relocatable package format versions.
To do this easily, we added ".relocatable_package_version" file on
relocatable package.
If .relocatable_package_version exists and it contains "2",
all files under the package is located "scylla*/" subdirectory.
If not, it's legacy format package.
> ccmlib/scylla_repository: support relocatable package format v2

- ccmlib/scylla_node.py
This reverts commit 240ea4a41a490ce3480473b92111ffacb60dc720.
> Revert "fix(scylla_manager): Added a provider to the agent's s3 config"

- ccmlib/common.py
When node.nodetool is called in parallel by multiple threads
it ends up calling node.get_env -> make_cassandra_env
in parallel.
That may leave `node<i>/bin/cassandra.in.sh` empty, as seen
in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/535/testReport/nodetool_additional_test/TestNodetool/concurrent_repair_test/
Fix that by having only one thread by default
preparing the node's `cassandra.in.sh`
(the one that calls with update_conf=True),
and the others waiting for 1 second for it to finish.
In any case, other threads may prepare `cassandra.in.sh`
in parallel as each is writing first to a unique
temporary file and then atomically renaming it
to the final name.  The waiting by the other threads
is for efficiency rather than correctness.
Fixes #240 …
> ccmlib/common: fix parallel invokation of make_cassandra_env

- ccmlib/scylla_cluster.py
Due to changes in the configuration after manager 2.1, the segments_per_repair config option can no longer be used.
As such, I added a condition that checks whether the manager version that is being used supports segments_per_repair.
> fix(manager): Added version-dependent configuration

- pytest.ini
Added config files for pytest framework
> feature(pytest): Added pytest config flies

- ccmlib/node.py
- ccmlib/scylla_docker_cluster.py
made `nodetool` command work to docker nodes
> make nodetool commands work for docker nodes

- tests/test_scylla_docker_cluster.py
added 1st test to check if `nodetool status` returns the expected values
> Docker ccm nodetool status test

- ccmlib/scylla_node.py
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/303/testReport/junit/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_low_to_half_test/
it may take a long time for a node to start in debug mode when it needs to reshard its tables.
```
File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
yield
File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
testMethod()
File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/materialized_views_test.py", line 2029, in interrupt_build_process_with_resharding_low_to_half_test
self._do_resharding_test('1', str(cpu_count() // 2))
File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dt …
```
> ccmlib/scylla_node: wait also for resharding on startup

- ccmlib/scylla_docker_cluster.py
* Create share directory for RSA keys
>     feature(scylla_docker_cluster.py): Enabling SSL keys

- .github/workflows/integration-tests.yml
- ccmlib/common.py
- ccmlib/scylla_docker_cluster.py
- tests/test_config.py
Added support for passing replace-address argument
> feature(docker_args): Support passing args to scylla docker

- ccmlib/cluster.py
- ccmlib/node.py
- ccmlib/scylla_cluster.py
- ccmlib/scylla_node.py
Added support of node upgrade and method that upgrade
whole cluster
I opened this PR as Draft because of I want to run byo dtest and validate that it doesn't broke other tests
> Support node upgrade procedure

- ccmlib/common.py
- ccmlib/scylla_node.py
* Convert all `open` to` with open` to ensure the file will close
after the used
> fix: Fixing all ResourceWarning messages

- ccmlib/scylla_node.py
cassandra.in.sh file is created during ckuster creation and need be removed after upgrade
> Add method to clean runtime file after upgrade

- ccmlib/scylla_repository.py
This PR will change download of relocatable's behavior.
Now if SCYLLA_JMX_PACKAGE / SCYLLA_TOOLS_JAVA_PACKAGE or SCYLLA_JAVA_TOOLS_PACKAGE / SCYLLA_CORE_PACKAGE environment variables are supplied (it happens when running dtest from Jenkins, packages are downloaded before the tests are started and Scylla version is some random and long string - SHA - that not include ":"), those packages will be used.
But this mechanism is wrong in case upgrade test: during the test we need to download relocatable's for different versions. But if  packages environment variables for tested version were supplied, the upgrade version won't be downloaded. It will use packages environment variables instead of version number.
This PR won't take packages environment variables if version with ":" is supplied …
> Raise priority of SCYLLA_VERSION in presence of packages in environment variable

- ccmlib/scylla_repository.py
Add support for new enterprise relocatable package link
> fix(scylla_repository): Support old and new enterprise relocatable links

- ccmlib/scylla_node.py
Since cassandra dropped thrift support it is possible that at some point ccm
can get request to deploy nodes/cluster with thrift_interface=None
which is currently results in python errors
> fix(scylla_node): covering cases when network_interfaces records could be None

- ccmlib/scylla_node.py
Currently, if the node is not running for any reason,
failed to start, aborted, etc., do_stop does not
stop pscylla-jmx, which it should.
This change just ignores the node running status
and attempts to stop/kill all related processes that
appear to run.
Fixes #309
> scylla_node: do_stop: ignore node.is_running

- ccmlib/scylla_node.py
This reverts commit 811bf0c424b2b50145c29e7605341882a3ac5954.
> Revert "fix(scylla_node): covering cases when network_interaces records could be None"

- ccmlib/scylla_cluster.py
Added agent_download_files function.
The function receives a node object, bucket location list and a snapshot tag
and afterwards uses the agent's download-files command to download the snapshot
files to the node's upload directory.
optional -  keyspace_filter_list: list of glob strings. only the files of keyspaces
that match the glob filters will be downloaded.
> feature(manager-agent): function to execute download-files command

- ccmlib/scylla_node.py
In manager 2.4, the manager's cluster update command received a new arg,
--port, which, upon use, config the manager server to communicate with the
agents via the requested port. As such, I added a new function that
will allow the user to alter the agent's config, to set the new used port
> feature(manager): Added an option to reconfigure the agent

- ccmlib/scylla_repository.py
Master builds use a naming scheme that is a bit different from the next builds,
and using such build will cause an exception because of it.
Specifically, the scylla_package is called scylla-x86_64-package.tar.gz instead
of scylla-package.tar.gz.
I modified the setup function to support both options.
> fix(scylla_version): modified to be able to use master builds

- ccmlib/scylla_cluster.py
Since in some of the manager tests we create more then one cluster,
with the intent to add the second cluster to the manager that was created
with the first cluster, starting another manager server is unnecessary.
As such, I added an option to not start the manager server specifically
when creating a cluster - the skip_manager_server parameter.
It's important to note that option only stops the manager server from
being created, but not the agents.
> feature(manager): option to not start the manager server on cluster creation

- scripts/download_enterprise.sh
location of the relocatable packages tree move to a diffrent location
> scripts/download_enterprise: download version from new S3 location

- ccmlib/scylla_repository.py
https://trello.com/c/Hc4c6Cqy/4354-fix-ccm-to-support-new-relocatible-files-layout
From 4.6 we started releasing arm arch along with x86_64.
Because of that some of the package names had changed from `scylla-package.tar.gz` to `scylla-x86_64-package.tar.gz`
on both unstable and releases.
> fix(scylla_repository.py): make it work properly with arch

- ccmlib/node.py
> Fix to make Cassandra 4.0 working and starting

- ccmlib/node.py
Currently wait_for_compactions has no timeout
so it can loop forever if compaction gets stuck
and never completes.
To detect that earlier provide a timeout
(300 seconds by default) after which, if
compactionstats show no progress, the function
raises a TimeoutError.
DTest: compaction_additional_test.py::TestCompactionAdditional::test_compaction_removes_ttld_data_by_time_windows
> node: wait_for_compactions: add idle timeout

- ccmlib/common.py
- ccmlib/scylla_node.py
The method is generic and can be "call" from each file in the package
> style(common.py): Moving wait_for from scylla_node

- ccmlib/cluster.py
Add option to keep folder of removed node
> improvement(remove node): keep removed node folder

- ccmlib/scylla_node.py
Restore tables of system and system_schema keyspaces during rollback from snapshot that has been
taken before upgrade.
Issue: https://github.com/scylladb/scylla-enterprise/issues/1950
Restore system tables documentation:
https://docs.scylladb.com/upgrade/upgrade-enterprise/upgrade-guide-from-2018.1-to-2019.1/upgrade-guide-from-2018.1-to-2019.1-rpm/#restore-system-tables
> fix(rollback): restore system tables

- ccmlib/scylla_node.py
Added a new property to get build-id from Scylla executable
Trello task - [link](https://trello.com/c/Azr2BxnM/4776-pr9517-several-virtual-tables-have-been-added-for-providing-information-usually-obtained-via-nodetool-systemsnapshots-systemprot) 
Related dtest PR - [link](https://github.com/scylladb/scylla-dtest/pull/2691)
> feat(scylla_node.py): get build-id from scylla binary

- ccmlib/scylla_node.py
`--kernel-page-cache` and `--max-networking-io-control-blocks` are turned on only for specific Scylla versions that support it. The check `version >= 4.5.dev` was incorrect for Enterprise releases, because it matched for all Enterprise versions (2020.1 >= 4.5), even those that don't support those flags.
Fix by checking if the version is an Enterprise version and having a separate minimum Enterprise version for those flags.
Fixes #384
> fix(scylla_node.py): version checks for Enterprise

- ccmlib/utils/sni_proxy.py
since not in all cases we can assume correclty
which part of the output are the json we are looking
for, and which are not.
> utils/sni_proxy.py: make cqlsh json lookup more robust

- ccmlib/scylla_repository.py
Following the work done in scylladb/scylla-pkg#3035 and in https://github.com/scylladb/scylla-dtest/pull/2816
align also ccm to work with both old and new prefixes
> ccmlib/scylla_repository.py: Use new reloc package prefix

- ccmlib/scylla_repository.py
In recent code we introduce a capability to download unified package tarball (insted of multiple packages), that code was found to be broken when running inside docker (without systemd).
install command needed to be alter a bit to disable some of the systemd related code (which in master currently can be disable via `--without-systemd`)
Ref: scylladb/scylladb#11898
Fix: scylladb/scylla-dtest#2895
> fix(unified-package): fix install of older version unified packages

- ccmlib/scylla_node.py
* add a tiny helper to convert memory size like "1G" to 1024^3. seastar/src/util/conversions.cc supports IEC style postfixes, but since we don't use them, let's keep the implementation simple.
* expose ScyllaNode.memory() so dtest can use it when verifying the system_table. currently, in dtest's system_tables_test.py:TestRuntimeInfoTable, the total size of memory is passed in via `jvm_args` passed to self.prepare_cluster(). to improve the readability, and to be more future-proof, it'd be simpler to expose this setting from node. so dtest can verify the total size of memory exposed by system table by comparing it with the value exposed by node instead of a magic number of keep "1G" as a member variable of the test.
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>
> scylla_node: expose --memory in bytes

- ccmlib/scylla_node.py
To be used for replacing a node given its host_id
rather than its ip address.
Makes use of the newly added --replace-node-first-boot scylla option.
> scylla_node: start: add replace_node parameter

- ccmlib/scylla_node.py
since scylladb/scylla-jmx@96adf0ef51ad49b6abb98867f73cf69705f5f3e3 introduced this new script, the ccm code should be looking for it, and using it insted of using the default java or hoping for the user to set JAVA_HOME correcrtly to JMX needs
Ref: https://github.com/scylladb/scylla-jmx/commit/96adf0ef51ad49b6abb98867f73cf69705f5f3e3
> use jmx `select-java` script to execute jmx

- ccmlib/scylla_node.py
Convenience method allowing the invocation of the scylla-sstable tool, built into the scylla sstable. The method uses the same mechanism for selecting which sstable to work on, as Node.run_sstable2json(). But other than that, there are notable differences, run_scylla_sstable():
* Allows for accessing all scylla-sstable operations, not just dump-data (the scylla-sstable equivalent to sstable2json).
* Allows direct pass-through of command-line arguments to the underlying scylla-sstable invokation. This ensures maximum forward-compatibility, without the need to patch this method each time the underlying code's capabilities change.
* Has a batch mode, which allows for passing all sstables at once to scylla-sstable (which accepts 1 or more sstable args).
* It looses the `enumerate_keys` …
> scylla_node: add run_scylla_sstable()

- ccmlib/scylla_repository.py
now that we want to start using manager in parallel tests we need to make sure we don't try to download into the same direcotry at the same time.
> scylla_repository: use LockFile for manager downloads

- ccmlib/scylla_node.py
`scylla sstable dump-data` errors out when there are no sstables specified. but we expect a simple API exposed by `dump_sstables()`, so that its caller does not have to handle the error in this case. so, in this change, we just change `run_scylla_sstable()` so that it fills an empty list in the json returned in the dict.
this should enable `dump_sstable()` to continue work. and its caller should be happy now.
also, this change removes the unused `env` local variable.
> scylla_node: do not error out when no sstables to dump

- ccmlib/node.py
also update the comment to reflect the latest changes.
this should enable the dtest to test with uuid-based sstable identifiers enabled.
> node: let sstable_regexp match with sstable with uuid generation

- ccmlib/scylla_node.py
`ScyllaNode.dump_sstables()` is a wrapper around
`ScyllaNode.run_scylla_sstable()`. it provides a more user friendly interface than the latter. it is introduced so that tests can use it with less pain when migrating from
`node.run_sstablemetadata()` to `node.run_scylla_sstable()`.
> scylla_node: add ScyllaNode.dump_sstable_stats()

- ccmlib/node.py
in 5cb0985a, we tried harder to remove more unsealed sstables. but that's not enough. there is chances that scylla leaves us with a single '*-TOC.txt.tmp' component, without corresponding '*-Data.db'. in that case, `sstablelevelreset` still fails when trying to open all tables in the sstable data directory.
so, in this change, instead of enumerating the sstables by globbing '*Data.db', we just glob '*TOC.txt.tmp'. and remove all components sharing the same prefix. this will clean *all* unsealed sstables files.
Fixes https://github.com/scylladb/scylladb/issues/15210
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>
> ccmlib/node: cleanup unsealed sstables without Data.db component

- ccmlib/scylla_node.py
scylla_node: add a helper for accessing environ variables
before this change, we always try to access `self._launch_env`
and fall back to `os.environ`, and optionally update the
return env dict, then use it. the pattern repeats itself
couple times in ScyllaNode class.
in this change, to consolidate it, a helper is added. it
does not do anything clever just preserve existing behavior.
despite that existing behavior could be potentially
confusing: we actually _mutate_ the returned dict if
it references the existing `self._launch_env`.
> scylla_node: add a helper for accessing environ variables

- ccmlib/utils/sni_proxy.py
since we are having random issue in CI with DNS
of dockerhub, we'll try to build it again
a few time, until the images would get pulled
Later on the same job/machine, we do see it working again. so we do belive it's temporary
Fixes: https://github.com/scylladb/scylla-dtest/issues/3592
> ccmlib.utils.sni_proxy: add retry to docker build

- ccmlib/scylla_node.py
* since we want to use this for encrypted sstable, we need to pass in the scylla.yaml
* since some of the output has binary data inside it, we need to make the call using bytes and not text
> ccmlib/scylla_node: pass `scylla.yaml` to `scylla sstable`

- ccmlib/scylla_node.py
> ccmlib/scylla_node: use the new style super() without arguments

- ccmlib/scylla_node.py
We'd like to deprecate collectd, we use Prometheus these days. Refs: scylladb/scylla-enterprise#3628
> Remove --collectd option

- ccmlib/scylla_node.py
since we have cases multiple `--experimental-features` needs to be passed via `SCYLLA_EXT_OPTS`, adding support for key with multiple values in `process_opts()`
fixes: #540
closes: #541
> support multiple identical args in SCYLLA_EXT_OPTS

- ccmlib/utils/inotify.py
- tests/test_utils_inotify.py
a typical session looks like:
```console
$ while true; do
sleep 1
echo 1 >> /tmp/foobar
done
```
in the meanwhile:
```py
from inotify import INotify, Flag
notify = INotify()
with notify.watch("/tmp/foobar", Flag.MODIFY):
for e in notify.read():
print(e)
```
> ccmlib/utils: add inotify wrapper

- ccmlib/scylla_node.py
servel place in the code were assuming that `api_port` would be 10000.
some tests in the java-driver we setting `api_port` to a random port hence breaking some of the ccm functionality, like nodetool and wait_for_other_notice logic
> ccmlib/scylla_node: stop hardcoding `api_port`

- ccmlib/scylla_node.py
> ccmlib/scylla_node: use functools.cached_property to define has_jmx

- ccmlib/scylla_node.py
since the `scylla sstable` code doesn't fallback into any other option but reading schema from sstable of system tables, if `--scylla-yaml-file` is used.
switching to `SCYLLA_CONF` env variable should make the tool use other fallback options like reading the assuming the schema from the sstable we want to read.
Ref: https://github.com/scylladb/scylla-enterprise/issues/4660
> scylla_node: switch from `--scylla-yaml-file` to `SCYLLA_CONF` env variable

- ccmlib/common.py
in some situations, like when running cassandra 4.1, we can endup with some of the commands in this function return multiple pids and not just one process
to handle that we just return all of the pids back. in the enad it's just used for debug printing about who's holding the ports.
> ccmlib/common.py: update `pid_listening_on` to return multiple pids

- ccmlib/cmds/cluster_cmds.py
Option is already there, only thing left is to expose it.
> Expose `--rack` option for `ccm add` cli

- ccmlib/scylla_node.py
When running scylla-sstable, sstables passed to the tool are prone to disappearing as a result of a concurrent compaction. To prevent this, callers are required to disable compaction on the table from which sstables are dumped. With tablets, new ways for sstables to disappear were introduced: migration, split and merge. Instead of piling on more responsibilities on the caller, ensure that sstables are stable during the dump internally: create a snapshot and dump the sstables from the snapshot. The snapshot is cleared after the dump, or left in place in case of error (for post-mortem analysis).
If the caller doesn't provide a keyspace, or they provide a specific list of datafiles to be dumped, they still have to ensure that they are stable.
After this change, the caller is still expected …
> ccmlib/scylla_node.py: run_scylla_sstable(): dump sstables from a snapshot
